In [2]:
#Create Dataset
import pandas as pd

sales = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Monitor", "Keyboard"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara", "Ali", "Neda"
    ],
    "region": [
        "North", "South", "West", "East",
        "North", "East", "South", "West",
        "North", "South", "East", "West"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12, 4, 6],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25, 400, 50]
})

sales["revenue"] = sales["quantity"] * sales["price"]

In [3]:
#review aggregation
sales['revenue'].sum()

np.int64(10475)

In [4]:
sales['revenue'].mean()

np.float64(872.9166666666666)

In [5]:
sales['revenue'].max()

2000

In [6]:
sales['revenue'].min()

250

In [7]:
sales['revenue'].median()

600.0

In [8]:
sales['revenue'].count()

np.int64(12)

In [9]:
sales['revenue'].nunique()

9

In [10]:
#What is the total revenue for each product?
sales.groupby('product')['revenue'].sum()

product
Keyboard     950
Laptop      5000
Monitor     3600
Mouse        925
Name: revenue, dtype: int64

1-
Aggregation alone
        ↓
Whole dataset
        ↓
"How much did we sell?"

2-
groupby + aggregation
        ↓
Separate groups
        ↓
"How much did we sell for each product?"

In [15]:
#For every product, find:
#- total revenue
#- average revenue
#- minimum revenue
#- maximum revenue
#- total quantity

sales.groupby('product', as_index=False).agg(
    total_revenue=('revenue','sum'),
    average_revenue=('revenue','mean'),
    minimum_revenue=('revenue','min'),
    maximum_revenue=('revenue','max'),
    total_quantity=('quantity','sum')
)
#This is called MULTIPLE AGGREGATION

,product,total_revenue,average_revenue,minimum_revenue,maximum_revenue,total_quantity
0,Keyboard,950,316.666667,250,400,19
1,Laptop,5000,1666.666667,1000,2000,5
2,Monitor,3600,1200.000000,800,1600,9
3,Mouse,925,308.333333,250,375,37

Group the sales by salesperson and calculate:
- total revenue
- average revenue
- total quantity
- number of orders

Your target structure should be:
salesperson | total_revenue | average_revenue | total_quantity | number_of_orders

In [16]:
sales.groupby('salesperson',as_index=False).agg(
    total_revenue = ('revenue','sum'),
    average_revenue = ('revenue','mean'),
    total_quantity = ('quantity','sum'),
    number_of_order = ('order_id','count')
)

  salesperson  total_revenue  average_revenue  total_quantity  number_of_order
0         Ali           4225      1056.250000              26                4
1        Neda            300       300.000000               6                1
2        Reza           3400      1133.333333              11                3
3        Sara           2550       637.500000              27                4

In [18]:
#Multi-column groupby()
#Create a separate group for every region/product combination.
sales.groupby(['region','product'],as_index=False).agg(
    total_revenue = ('revenue','sum'),
    total_quantity = ('quantity','sum')
)

  region   product  total_revenue  total_quantity
0   East    Laptop           1000               1
1   East   Monitor           1600               4
2   East     Mouse            375              15
3  North    Laptop           4000               4
4  North   Monitor           1200               3
5  South  Keyboard            400               8
6  South     Mouse            550              22
7   West  Keyboard            550              11
8   West   Monitor            800               2

In [19]:
#Add sorting
sales.groupby(['region','product'],as_index=False).agg(
    total_revenue = ('revenue','sum'),
    total_quantity = ('quantity','sum')
).sort_values(by='total_revenue',ascending=False)

  region   product  total_revenue  total_quantity
3  North    Laptop           4000               4
1   East   Monitor           1600               4
4  North   Monitor           1200               3
0   East    Laptop           1000               1
8   West   Monitor            800               2
7   West  Keyboard            550              11
6  South     Mouse            550              22
5  South  Keyboard            400               8
2   East     Mouse            375              15

PATTERN : 
GROUP
  ↓
AGGREGATE
  ↓
SORT

In [22]:
#Filtering before groupby()
#For only the North and East regions, what is the performance of each salesperson?
sales.loc[sales['region'].isin(['North','East'])].groupby('salesperson',as_index=False).agg(total_revenue=('revenue','sum')).sort_values(by='total_revenue')

  salesperson  total_revenue
2        Sara           1200
1        Reza           3000
0         Ali           3975

PATTERN:
FILTER
   ↓
GROUP
   ↓
AGGREGATE
   ↓
SORT

In [23]:
#Mini Analyst Project

#Give me a performance report for each salesperson. I want to know how much they sold, how many units they sold, how many orders they handled, and their average order value.

In [25]:
sales.groupby('salesperson',as_index=False).agg(
    total_revenue = ('revenue','sum'),
    count_of_order = ('order_id','count'),
    average_revenue = ('revenue','me')
)

  salesperson  total_revenue  count_of_order  average_revenue
0         Ali           4225               4      1056.250000
1        Neda            300               1       300.000000
2        Reza           3400               3      1133.333333
3        Sara           2550               4       637.500000