In [1]:
#set dataframe
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "order_id": ["1001", "1002", "1002", "1003", "1004"],
    "customer": ["Ali", "Sara", "Sara", "Reza", "Neda"],
    "sales": ["1200", "850", "850", "1,500", "900"],
    "order_date": [
        "2026-01-10",
        "2026-01-11",
        "2026-01-11",
        "2026-01-12",
        "2026-01-13"
    ]
})

print(df)
print(df.info())
print(df.dtypes)

  order_id customer  sales  order_date
0     1001      Ali   1200  2026-01-10
1     1002     Sara    850  2026-01-11
2     1002     Sara    850  2026-01-11
3     1003     Reza  1,500  2026-01-12
4     1004     Neda    900  2026-01-13
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      object
 1   customer    5 non-null      object
 2   sales       5 non-null      object
 3   order_date  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes
None
order_id      object
customer      object
sales         object
order_date    object
dtype: object

In [2]:
#Find and remove duplicates
#Detect duplicate rows with duplicated()
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

Pandas returns a Boolean Series: True for rows considered duplicates and False otherwise.

In [4]:
#Inspect the duplicate rows:
df.loc[df.duplicated()]

  order_id customer sales  order_date
2     1002     Sara   850  2026-01-11

In [5]:
#Count them:
df.duplicated().sum()

np.int64(1)

In [6]:
#Remove duplicate rows with drop_duplicates()
df_clean = df.drop_duplicates()
df_clean

  order_id customer  sales  order_date
0     1001      Ali   1200  2026-01-10
1     1002     Sara    850  2026-01-11
3     1003     Reza  1,500  2026-01-12
4     1004     Neda    900  2026-01-13

This keeps the first occurrence and removes subsequent identical rows.

In [7]:
#Find duplicates based on selected columns
df.loc[df.duplicated(subset=['order_id'])]

  order_id customer sales  order_date
2     1002     Sara   850  2026-01-11

This checks duplicates using only order_id.

In [8]:
#inspect every row belonging to a repeated order ID:
df.loc[df.duplicated(subset=['order_id'],keep=False)]

  order_id customer sales  order_date
1     1002     Sara   850  2026-01-11
2     1002     Sara   850  2026-01-11

The keep=False argument marks all occurrences of duplicated values as True, including the first one.

In [10]:
#Choose which duplicate to keep
#The keep argument controls what duplicated() marks and what drop_duplicates() removes.
#keep="first"	Keep the first occurrence (default)
#keep="last"	Keep the last occurrence
#keep=False	Mark or remove every occurrence in a duplicate group
df_clean = df.drop_duplicates(keep=False)
df_clean

  order_id customer  sales  order_date
0     1001      Ali   1200  2026-01-10
3     1003     Reza  1,500  2026-01-12
4     1004     Neda    900  2026-01-13

Important analyst warning: Don't automatically remove every repeated order ID. In a real dataset, one order may contain several product lines. Before deleting records, determine whether the repeated ID represents a genuine duplicate or a legitimate multi-line order.

practical duplicate investigation:
Before removing duplicates, ask:
- Are all columns identical?
- Is the identifier supposed to be unique?
- Could repeated IDs represent separate products within one order?
- If records conflict, is there a reliable rule for deciding which one to retain?

In [12]:
#Understand and convert data types
#Data types tell Pandas how to interpret the values in each column.
#Inspect data types
df.dtypes

order_id      object
customer      object
sales         object
order_date    object
dtype: object

Common Pandas data types include:
Data type	Meaning	Example
int64	Integer numbers	100, 250
float64	Decimal numbers	12.5, 99.99
object	Often text or mixed values	"hello", "1500"
string	Text values	"Tehran"
bool	True/False	True, False
datetime64[ns]	Date/time values	2026-01-10

In [13]:
#Convert text to numbers with astype()
df['sales'] = df['sales'].astype(float)
df.dtypes

ValueError: could not convert string to float: '1,500'

In [14]:
#Handle messy numeric columns
df['sales'] = df['sales'].str.replace(',','',regex=False)
df['sales'] = df['sales'].astype(float)
df.dtypes

order_id       object
customer       object
sales         float64
order_date     object
dtype: object

In [15]:
df

  order_id customer   sales  order_date
0     1001      Ali  1200.0  2026-01-10
1     1002     Sara   850.0  2026-01-11
2     1002     Sara   850.0  2026-01-11
3     1003     Reza  1500.0  2026-01-12
4     1004     Neda   900.0  2026-01-13

In [16]:
#Handle messy numeric columns with pd.to_numeric()
df['sales']= pd.to_numeric(df['sales'], errors='raise')

In [17]:
df

  order_id customer   sales  order_date
0     1001      Ali  1200.0  2026-01-10
1     1002     Sara   850.0  2026-01-11
2     1002     Sara   850.0  2026-01-11
3     1003     Reza  1500.0  2026-01-12
4     1004     Neda   900.0  2026-01-13

The errors argument matters:
- "raise" — raise an error when conversion fails; useful when you want to catch unexpected values.
- "coerce" — convert invalid values to missing values (NaN).

In [18]:
values = pd.Series(["100", "250", "unknown"])
values = pd.to_numeric(values, errors='coerce')

In [19]:
values

0    100.0
1    250.0
2      NaN
dtype: float64

In [20]:
#Convert text to dates with pd.to_datetime()
df['order_date'] = pd.to_datetime(df['order_date'], errors='raise')

In [22]:
df.dtypes

order_id              object
customer              object
sales                float64
order_date    datetime64[ns]
dtype: object

In [25]:
#Now we can extract the year, month, or day:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df

  order_id customer   sales order_date  order_year  order_month  order_day
0     1001      Ali  1200.0 2026-01-10        2026            1         10
1     1002     Sara   850.0 2026-01-11        2026            1         11
2     1002     Sara   850.0 2026-01-11        2026            1         11
3     1003     Reza  1500.0 2026-01-12        2026            1         12
4     1004     Neda   900.0 2026-01-13        2026            1         13

In [28]:
#For inconsistent or potentially invalid dates:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

In [29]:
df

  order_id customer   sales order_date  order_year  order_month  order_day
0     1001      Ali  1200.0 2026-01-10        2026            1         10
1     1002     Sara   850.0 2026-01-11        2026            1         11
2     1002     Sara   850.0 2026-01-11        2026            1         11
3     1003     Reza  1500.0 2026-01-12        2026            1         12
4     1004     Neda   900.0 2026-01-13        2026            1         13

Invalid dates become NaT (Pandas' missing datetime value). As with numeric conversion, inspect any newly missing values afterward.

In [30]:
#Hands-on cleaning workflow
#set messy dataframe
messy_sales = pd.DataFrame({
    "order_id": ["1001", "1002", "1002", "1003", "1004"],
    "city": [" Tehran ", "shiraz", "shiraz", "TEHRAN", None],
    "sales": ["1,200", "850", "850", "unknown", "900"],
    "order_date": [
        "2026-01-10",
        "2026-01-11",
        "2026-01-11",
        "2026-01-12",
        "2026-01-13"
    ]
})

In [31]:
messy_sales

  order_id      city    sales  order_date
0     1001   Tehran     1,200  2026-01-10
1     1002    shiraz      850  2026-01-11
2     1002    shiraz      850  2026-01-11
3     1003    TEHRAN  unknown  2026-01-12
4     1004      None      900  2026-01-13

In [32]:
#Inspect before cleaning
messy_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      object
 1   city        4 non-null      object
 2   sales       5 non-null      object
 3   order_date  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [33]:
messy_sales.dtypes

order_id      object
city          object
sales         object
order_date    object
dtype: object

In [34]:
messy_sales.isna().sum()

order_id      0
city          1
sales         0
order_date    0
dtype: int64

In [35]:
messy_sales.duplicated().sum()

np.int64(1)

In [36]:
#Standardize the city text
messy_sales['city'] = (
    messy_sales['city']
    .str.strip()
    .str.title()
)
messy_sales

  order_id    city    sales  order_date
0     1001  Tehran    1,200  2026-01-10
1     1002  Shiraz      850  2026-01-11
2     1002  Shiraz      850  2026-01-11
3     1003  Tehran  unknown  2026-01-12
4     1004    None      900  2026-01-13

In [38]:
#Convert sales to numeric values
messy_sales['sales'] = messy_sales['sales'].str.replace(',','',regex=False)
messy_sales['sales'] = pd.to_numeric(messy_sales['sales'], errors='coerce')
messy_sales

  order_id    city   sales  order_date
0     1001  Tehran  1200.0  2026-01-10
1     1002  Shiraz   850.0  2026-01-11
2     1002  Shiraz   850.0  2026-01-11
3     1003  Tehran     NaN  2026-01-12
4     1004    None   900.0  2026-01-13

In [39]:
messy_sales.loc[messy_sales['sales'].isna()]

  order_id    city  sales  order_date
3     1003  Tehran    NaN  2026-01-12

In [40]:
#Convert dates
messy_sales['order_date'] = pd.to_datetime(messy_sales['order_date'], errors='coerce')
messy_sales.dtypes

order_id              object
city                  object
sales                float64
order_date    datetime64[ns]
dtype: object

In [41]:
#Remove exact duplicate rows
clean_sales = messy_sales.drop_duplicates()
clean_sales

  order_id    city   sales order_date
0     1001  Tehran  1200.0 2026-01-10
1     1002  Shiraz   850.0 2026-01-11
3     1003  Tehran     NaN 2026-01-12
4     1004    None   900.0 2026-01-13

In [59]:
#solve NaN value
clean_sales['sales'] = clean_sales['sales'].fillna(clean_sales['sales'].mean())
clean_sales['city'] = clean_sales['city'].fillna('Unknown')
clean_sales

C:\Users\HP\AppData\Local\Temp\ipykernel_7928\3404223194.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_sales['sales'] = clean_sales['sales'].fillna(clean_sales['sales'].mean())
C:\Users\HP\AppData\Local\Temp\ipykernel_7928\3404223194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_sales['city'] = clean_sales['city'].fillna('Unknown')

  order_id     city        sales order_date
0     1001   Tehran  1200.000000 2026-01-10
1     1002   Shiraz   850.000000 2026-01-11
3     1003   Tehran   983.333333 2026-01-12
4     1004  Unknown   900.000000 2026-01-13

In [60]:
#Validate
clean_sales.dtypes

order_id              object
city                  object
sales                float64
order_date    datetime64[ns]
dtype: object

In [61]:
clean_sales.isna().sum()

order_id      0
city          0
sales         0
order_date    0
dtype: int64

In [62]:
clean_sales.duplicated().sum()

np.int64(0)

SUMMARY OF DAY 41 :
Detect duplicate rows	df.duplicated()
Find every occurrence in a duplicate group	df.duplicated(subset=[...], keep=False)
Remove duplicate records	df.drop_duplicates()
Inspect data types	df.dtypes or df.info()
Convert to numbers	pd.to_numeric()
Convert to dates	pd.to_datetime()
Convert to a specified type	.astype()