In [1]:
#set up dataset
import pandas as pd

sales = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Monitor", "Keyboard"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara", "Ali", "Neda"
    ],
    "region": [
        "North", "South", "West", "East",
        "North", "East", "South", "West",
        "North", "South", "East", "West"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12, 4, 6],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25, 400, 50]
})

sales["revenue"] = sales["quantity"] * sales["price"]

sales.head()

,order_id,product,category,salesperson,region,quantity,price,revenue
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
1,1002,Mouse,Accessories,Sara,South,10,25,250
2,1003,Keyboard,Accessories,Ali,West,5,50,250
3,1004,Laptop,Electronics,Reza,East,1,1000,1000
4,1005,Monitor,Electronics,Sara,North,3,400,1200

In [2]:
#Explore the data
#How many rows and columns are in the dataset?
sales.shape

(12, 8)

In [3]:
#What are the column names?
sales.columns

Index(['order_id', 'product', 'category', 'salesperson', 'region', 'quantity',
       'price', 'revenue'],
      dtype='str')

In [5]:
#What are the data types?
sales.dtypes

order_id       int64
product          str
category         str
salesperson      str
region           str
quantity       int64
price          int64
revenue        int64
dtype: object

In [7]:
#What is the average quantity?
sales.describe()

          order_id   quantity        price      revenue
count    12.000000  12.000000    12.000000    12.000000
mean   1006.500000   5.833333   368.750000   872.916667
std       3.605551   4.509250   410.947492   681.030163
min    1001.000000   1.000000    25.000000   250.000000
25%    1003.750000   2.000000    43.750000   300.000000
50%    1006.500000   4.500000   225.000000   600.000000
75%    1009.250000   8.500000   550.000000  1300.000000
max    1012.000000  15.000000  1000.000000  2000.000000

In [9]:
#total inforamtion
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     12 non-null     int64
 1   product      12 non-null     str
 2   category     12 non-null     str
 3   salesperson  12 non-null     str
 4   region       12 non-null     str
 5   quantity     12 non-null     int64
 6   price        12 non-null     int64
 7   revenue      12 non-null     int64
dtypes: int64(4), str(4)
memory usage: 900.0 bytes

In [10]:
#Filtering practice
#Show all orders where the quantity is greater than or equal to 5.
sales.loc[sales['quantity'] >= 5]

,order_id,product,category,salesperson,region,quantity,price,revenue
1,1002,Mouse,Accessories,Sara,South,10,25,250
2,1003,Keyboard,Accessories,Ali,West,5,50,250
5,1006,Mouse,Accessories,Ali,East,15,25,375
6,1007,Keyboard,Accessories,Reza,South,8,50,400
9,1010,Mouse,Accessories,Sara,South,12,25,300
11,1012,Keyboard,Accessories,Neda,West,6,50,300

In [11]:
#Show orders where: Category is "Electronics" and Revenue is greater than 1000
sales.loc[(sales['category'] == 'Electronics') & (sales['revenue'] > 1000)]

,order_id,product,category,salesperson,region,quantity,price,revenue
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
4,1005,Monitor,Electronics,Sara,North,3,400,1200
8,1009,Laptop,Electronics,Reza,North,2,1000,2000
10,1011,Monitor,Electronics,Ali,East,4,400,1600

In [12]:
#Show orders from the "North" or "East" regions.
sales.loc[sales['region'].isin(['North','East'])]

,order_id,product,category,salesperson,region,quantity,price,revenue
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
3,1004,Laptop,Electronics,Reza,East,1,1000,1000
4,1005,Monitor,Electronics,Sara,North,3,400,1200
5,1006,Mouse,Accessories,Ali,East,15,25,375
8,1009,Laptop,Electronics,Reza,North,2,1000,2000
10,1011,Monitor,Electronics,Ali,East,4,400,1600

In [13]:
#Show orders where:
#The salesperson is Ali or Sara
#Quantity is greater than 5
sales.loc[(sales['salesperson'].isin(['Ali','Sara'])) & (sales['quantity'] > 5)]

   order_id product     category salesperson region  quantity  price  revenue
1      1002   Mouse  Accessories        Sara  South        10     25      250
5      1006   Mouse  Accessories         Ali   East        15     25      375
9      1010   Mouse  Accessories        Sara  South        12     25      300

In [14]:
#Sorting practice
#Sort all orders by revenue, from highest to lowest.
sales.sort_values(by='revenue',ascending=False)

,order_id,product,category,salesperson,region,quantity,price,revenue
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
8,1009,Laptop,Electronics,Reza,North,2,1000,2000
10,1011,Monitor,Electronics,Ali,East,4,400,1600
4,1005,Monitor,Electronics,Sara,North,3,400,1200
3,1004,Laptop,Electronics,Reza,East,1,1000,1000
7,1008,Monitor,Electronics,Sara,West,2,400,800
6,1007,Keyboard,Accessories,Reza,South,8,50,400
5,1006,Mouse,Accessories,Ali,East,15,25,375
9,1010,Mouse,Accessories,Sara,South,12,25,300
11,1012,Keyboard,Accessories,Neda,West,6,50,300
1,1002,Mouse,Accessories,Sara,South,10,25,250
2,1003,Keyboard,Accessories,Ali,West,5,50,250

In [16]:
#Filter orders from the "Accessories" category, then sort by quantity from highest to lowest.
sales.loc[sales['category'] == 'Accessories'].sort_values(by='quantity',ascending=False)

,order_id,product,category,salesperson,region,quantity,price,revenue
5,1006,Mouse,Accessories,Ali,East,15,25,375
9,1010,Mouse,Accessories,Sara,South,12,25,300
1,1002,Mouse,Accessories,Sara,South,10,25,250
6,1007,Keyboard,Accessories,Reza,South,8,50,400
11,1012,Keyboard,Accessories,Neda,West,6,50,300
2,1003,Keyboard,Accessories,Ali,West,5,50,250

In [17]:
#Sort by:
#Category, ascending
#Revenue, descending
sales.sort_values(by=['category','revenue'],ascending=[True,False])

,order_id,product,category,salesperson,region,quantity,price,revenue
6,1007,Keyboard,Accessories,Reza,South,8,50,400
5,1006,Mouse,Accessories,Ali,East,15,25,375
9,1010,Mouse,Accessories,Sara,South,12,25,300
11,1012,Keyboard,Accessories,Neda,West,6,50,300
1,1002,Mouse,Accessories,Sara,South,10,25,250
2,1003,Keyboard,Accessories,Ali,West,5,50,250
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
8,1009,Laptop,Electronics,Reza,North,2,1000,2000
10,1011,Monitor,Electronics,Ali,East,4,400,1600
4,1005,Monitor,Electronics,Sara,North,3,400,1200
3,1004,Laptop,Electronics,Reza,East,1,1000,1000
7,1008,Monitor,Electronics,Sara,West,2,400,800

In [18]:
#Aggregation practice
#Total revenue across all orders
sales['revenue'].sum()

np.int64(10475)

In [19]:
#Average revenue per order
sales['revenue'].mean()

np.float64(872.9166666666666)

In [20]:
#Total quantity sold
sales['quantity'].sum()

np.int64(70)

In [21]:
#Maximum order revenue
sales['revenue'].max()

np.int64(2000)

In [24]:
#Total revenue from Electronics
sales.loc[sales['category'] == 'Electronics','revenue'].sum()

np.int64(8600)

In [25]:
#Average quantity for orders in the South region
sales.loc[sales['region'] == 'South','quantity'].mean()

np.float64(10.0)

In [26]:
#Total revenue from Ali’s orders
sales.loc[sales['salesperson'] == 'Ali','revenue'].sum()

np.int64(4225)

In [27]:
#For all orders, calculate the sum, mean, minimum, and maximum of revenue.
sales['revenue'].agg(['sum','mean','min','max'])

sum     10475.000000
mean      872.916667
min       250.000000
max      2000.000000
Name: revenue, dtype: float64

Analyze sales in the North and East regions. Focus on Electronics and Monitor orders. Show the matching orders from highest to lowest revenue, then report the total revenue, average revenue, and number of orders.

In [30]:
analys_result = sales.loc[(sales['region'].isin(['North','East'])) & (sales['category'].isin(['Electronics','Monitor']))].sort_values(by='revenue',ascending=False)
analys_result

,order_id,product,category,salesperson,region,quantity,price,revenue
0,1001,Laptop,Electronics,Ali,North,2,1000,2000
8,1009,Laptop,Electronics,Reza,North,2,1000,2000
10,1011,Monitor,Electronics,Ali,East,4,400,1600
4,1005,Monitor,Electronics,Sara,North,3,400,1200
3,1004,Laptop,Electronics,Reza,East,1,1000,1000

In [33]:
analys_result.agg({'revenue':['sum','mean','count'],'order_id':'count'})

       revenue  order_id
sum     7800.0       NaN
mean    1560.0       NaN
count      5.0       5.0

In [10]:
#Day28 - Complete project
##Advanced Analysis
#calculate total revenue for each product
sales.groupby('product')['revenue'].sum().sort_values(ascending=False)

product
Laptop      5000
Monitor     3600
Keyboard     950
Mouse        925
Name: revenue, dtype: int64

In [4]:
#Extend the analysis to show both total revenue and total quantity for each product.
sales.groupby('product').agg({'quantity':'sum','revenue':'sum'})

          quantity  revenue
product
Keyboard        19      950
Laptop           5     5000
Monitor          9     3600
Mouse           37      925

In [8]:
##Now analyze salespeople.
#Create a summary containing:
#Total revenue
#Average revenue per order
#Total quantity sold
#Number of orders
sales.groupby('salesperson').agg({'revenue':['sum','mean'],'quantity':['sum','count']})

            revenue              quantity
                sum         mean      sum count
salesperson
Ali            4225  1056.250000       26     4
Neda            300   300.000000        6     1
Reza           3400  1133.333333       11     3
Sara           2550   637.500000       27     4