In [1]:
#Set Dataset
import pandas as pd

df = pd.DataFrame({
    "customer": ["Ali", "Sara", "Reza", "Neda", "Hassan"],
    "age": [25, None, 31, None, 29],
    "city": ["Tehran", "Shiraz", None, "Tabriz", "Tehran"],
    "income": [1200, 1800, None, 1500, 2100]
})

df

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0     NaN     NaN
3     Neda   NaN  Tabriz  1500.0
4   Hassan  29.0  Tehran  2100.0

In [2]:
#find missing value
df.isna()

   customer    age   city  income
0     False  False  False   False
1     False   True  False   False
2     False  False   True    True
3     False   True  False   False
4     False  False  False   False

In [3]:
#find present value
df.notna()

   customer    age   city  income
0      True   True   True    True
1      True  False   True    True
2      True   True  False   False
3      True  False   True    True
4      True   True   True    True

In [4]:
#find not NaN in a column
df['age'].notna()

0     True
1    False
2     True
3    False
4     True
Name: age, dtype: bool

In [5]:
#find customer whose age is missing
df.loc[df['age'].isna()]

  customer  age    city  income
1     Sara  NaN  Shiraz  1800.0
3     Neda  NaN  Tabriz  1500.0

In [6]:
#Which customers have a known income?
df.loc[df['income'].notna()]

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
3     Neda   NaN  Tabriz  1500.0
4   Hassan  29.0  Tehran  2100.0

In [7]:
#Find records with missing age OR income
df.loc[(df['age'].isna()) | (df['income'].isna())]

  customer   age    city  income
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0     NaN     NaN
3     Neda   NaN  Tabriz  1500.0

In [8]:
#Find records with both age AND income present
df.loc[(df['age'].notna()) & (df['income'].notna())]

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
4   Hassan  29.0  Tehran  2100.0

In [9]:
#Count missing values per column
df.isna().sum()

customer    0
age         2
city        1
income      1
dtype: int64

In [10]:
#Count present values per column
df.notna().sum()

customer    5
age         3
city        4
income      4
dtype: int64

This tells us how many usable, non-missing entries each column contains. Whether those entries are actually valid still depends on the data.

In [13]:
#Count rows with at least one missing value
df.isna().any(axis=1).sum()

np.int64(3)

In [16]:
#Count rows where every value is present
df.notna().all(axis=1).sum()

np.int64(2)

any(axis=1) checks whether each row has at least one missing value.
all(axis=1) checks whether every column in a row is present.

In [17]:
#Practice
#set practice dataframe
practice = pd.DataFrame({
    "customer": ["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"],
    "age": [25, None, 31, 28, None, 35],
    "city": ["Tehran", "Shiraz", None, "Tabriz", "Tehran", None],
    "income": [1200, 1800, None, 1500, None, 2100]
})

In [19]:
#Find all customers whose city is missing.
practice.loc[practice['customer'].isna()]

Empty DataFrame
Columns: [customer, age, city, income]
Index: []

In [20]:
#Find all customers whose age is present.
practice.loc[practice['age'].notna()]

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
2     Reza  31.0     NaN     NaN
3     Neda  28.0  Tabriz  1500.0
5   Maryam  35.0     NaN  2100.0

In [21]:
#ind customers whose age is missing OR whose income is missing.
practice.loc[(practice['age'].isna()) | (practice['income'].isna())]

  customer   age    city  income
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0     NaN     NaN
4   Hassan   NaN  Tehran     NaN

In [29]:
#Count how many rows have both age and income present.
practice.loc[(practice['age'].notna()) & (practice['income'].notna())].shape[0]

3

In [31]:
#Create a Boolean column named has_missing that is True if any field in the row is missing.
has_missing = practice.isna().any(axis=1)
has_missing

0    False
1     True
2     True
3    False
4     True
5     True
dtype: bool