In [2]:
#set dataframe
import pandas as pd

df = pd.DataFrame({
    "customer": ["Ali", "Sara", "Reza", "Neda", "Hassan"],
    "age": [25, None, 31, 28, None],
    "city": ["Tehran", "Shiraz", None, "Tabriz", "Tehran"],
    "income": [1200, 1800, 1500, None, 2100]
})

df

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0

In [6]:
#By default, dropna() removes every row that contains at least one missing value.
clean_df = df.dropna()
clean_df

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0

In [7]:
df.shape

(5, 4)

In [8]:
clean_df.shape

(1, 4)

In [9]:
#df.dropna() = df.dropna(axis=0, how="any")
df.dropna(axis=0,how='any')

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0

axis=0: work with rows.
how="any": remove a row if at least one value is missing.

In [10]:
#Remove columns containing any missing value
df.dropna(axis=1)

  customer
0      Ali
1     Sara
2     Reza
3     Neda
4   Hassan

This removes any column containing at least one missing value

In [11]:
#Keep rows where at least one value is present
df.dropna(axis=0, how='all')

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0

!!! IMPORTANT : Removing a row because any value is missing can be too aggressive. Real datasets often have thousands of rows, and you don't want to throw away useful information unnecessarily.

In [14]:
#Check only important columns
#Imagine you're analyzing sales. An order without a Sales value may be unusable for a revenue analysis, but a missing City might not matter
df.dropna(subset=['income'])

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
4   Hassan   NaN  Tehran  2100.0

This removes rows where income is missing, while allowing missing values in other columns.

In [16]:
#We can check multiple columns
df.dropna(subset=['age','income'])

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
2     Reza  31.0    None  1500.0

This removes a row if age or income is missing. Both fields must be present for the row to remain.

In [22]:
#Require a minimum number of non-missing values : This is particularly useful when a dataset has many columns.
df.dropna(thresh=3)

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0

keep a row if it has at least 3 non-missing values.

In [23]:
#combine thresh with axis
df.dropna(thresh=4,axis=1)

  customer    city  income
0      Ali  Tehran  1200.0
1     Sara  Shiraz  1800.0
2     Reza    None  1500.0
3     Neda  Tabriz     NaN
4   Hassan  Tehran  2100.0

In [24]:
df.dropna(inplace=True)

In [25]:
df

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0

This modifies df directly instead of returning a separate cleaned DataFrame.

In [26]:
#Practice
import pandas as pd

customers = pd.DataFrame({
    "customer": ["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"],
    "age": [25, None, 31, 28, None, 35],
    "city": ["Tehran", "Shiraz", None, "Tabriz", "Tehran", None],
    "income": [1200, 1800, 1500, None, 2100, 2400]
})

print(customers)

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0
5   Maryam  35.0    None  2400.0

In [27]:
#Remove rows that contain at least one missing value.
customers.dropna(axis=0, how='any')

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0

In [28]:
#Remove only rows where every column is missing.
customers.dropna(axis=0,how='all')

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0
5   Maryam  35.0    None  2400.0

In [29]:
#Remove rows where income is missing, ignoring missing values in other columns.
customers.dropna(axis=0, subset=['income'])

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
4   Hassan   NaN  Tehran  2100.0
5   Maryam  35.0    None  2400.0

In [30]:
#Keep rows that have at least 3 non-missing values.
customers.dropna(axis=0, thresh=3)

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None  1500.0
3     Neda  28.0  Tabriz     NaN
4   Hassan   NaN  Tehran  2100.0
5   Maryam  35.0    None  2400.0

In [31]:
#Remove columns that have fewer than 5 non-missing values.
customers.dropna(axis=1, thresh=5)

  customer  income
0      Ali  1200.0
1     Sara  1800.0
2     Reza  1500.0
3     Neda     NaN
4   Hassan  2100.0
5   Maryam  2400.0