What is a merge key?
A merge key is a column (or combination of columns) that Pandas uses to identify matching records between two DataFrames.

In [2]:
#set dataframe
import pandas as pd
import numpy as np

customers = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "name": ["Ali", "Sara", "Reza"],
    "city": ["Tehran", "Shiraz", "Isfahan"]
})

orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003],
    "customer_id": [101, 102, 101],
    "amount": [500, 750, 300]
})

display(customers)
display(orders)

   customer_id  name     city
0          101   Ali   Tehran
1          102  Sara   Shiraz
2          103  Reza  Isfahan

   order_id  customer_id  amount
0      1001          101     500
1      1002          102     750
2      1003          101     300

In [3]:
#Use on when the matching column has the same name in both DataFrames.
merged = pd.merge(
    customers,
    orders,
    on='customer_id'
)
display(merged)

   customer_id  name    city  order_id  amount
0          101   Ali  Tehran      1001     500
1          101   Ali  Tehran      1003     300
2          102  Sara  Shiraz      1002     750

In [4]:
#Using left_on and right_on
#Two systems store the same information using different column names.
customers2 = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "customer_name": ["Ali", "Sara", "Reza"]
})
orders2 = pd.DataFrame({
    "order_id": [1001, 1002, 1003],
    "client_id": [101, 102, 101],
    "amount": [500, 750, 300]
})
display(customers2)
display(orders2)

   customer_id customer_name
0          101           Ali
1          102          Sara
2          103          Reza

   order_id  client_id  amount
0      1001        101     500
1      1002        102     750
2      1003        101     300

In [6]:
#Both columns represent the same information, but their names differ.
#Solution: left_on and right_on
result = pd.merge(
    customers2,
    orders2,
    left_on = 'customer_id',
    right_on = 'client_id',
    how = 'inner'
)
display(result)

   customer_id customer_name  order_id  client_id  amount
0          101           Ali      1001        101     500
1          101           Ali      1003        101     300
2          102          Sara      1002        102     750

In [7]:
#Because both columns contain the same matching identifiers, you might not need both in your final output.
result = result.drop(columns='client_id')
display(result)

   customer_id customer_name  order_id  amount
0          101           Ali      1001     500
1          101           Ali      1003     300
2          102          Sara      1002     750

In [8]:
#Working with multiple merge keys
#Sometimes a single key isn't sufficient to identify the correct match.
targets = pd.DataFrame({
    "product": ["Laptop", "Laptop", "Phone", "Phone"],
    "region": ["East", "West", "East", "West"],
    "target": [100, 150, 200, 250]
})
sales = pd.DataFrame({
    "product": ["Laptop", "Laptop", "Phone", "Phone"],
    "region": ["East", "West", "East", "West"],
    "actual_sales": [90, 170, 220, 230]
})
display(targets)
display(sales)

  product region  target
0  Laptop   East     100
1  Laptop   West     150
2   Phone   East     200
3   Phone   West     250

  product region  actual_sales
0  Laptop   East            90
1  Laptop   West           170
2   Phone   East           220
3   Phone   West           230

In [9]:
#Merge using two keys
result = pd.merge(
    targets,
    sales,
    on=['product','region']
)
display(result)

  product region  target  actual_sales
0  Laptop   East     100            90
1  Laptop   West     150           170
2   Phone   East     200           220
3   Phone   West     250           230

In [10]:
#Multiple keys with different names
left_df = pd.DataFrame({
    "product": ["Laptop", "Phone"],
    "region": ["East", "West"],
    "target": [100, 200]
})

right_df = pd.DataFrame({
    "item": ["Laptop", "Phone"],
    "sales_region": ["East", "West"],
    "actual": [90, 220]
})

display(left_df)
display(right_df)

  product region  target
0  Laptop   East     100
1   Phone   West     200

     item sales_region  actual
0  Laptop         East      90
1   Phone         West     220

In [13]:
result = pd.merge(
    left_df,
    right_df,
    left_on = ['product','region'],
    right_on = ['item','sales_region']
)
display(result)

  product region  target    item sales_region  actual
0  Laptop   East     100  Laptop         East      90
1   Phone   West     200   Phone         West     220

In [14]:
result = result.drop(columns=['item','sales_region'])
display(result)

  product region  target  actual
0  Laptop   East     100      90
1   Phone   West     200     220

In [15]:
#Index-based merging
#So far, we've merged using ordinary columns.
#But sometimes the key is stored in a DataFrame's index.
#Pandas provides left_index and right_index for this.
employees = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza"]
}, index=[101, 102, 103])

salaries = pd.DataFrame({
    "salary": [3000, 4000, 3500]
}, index=[101, 102, 104])

display(employees)
display(salaries)

     name
101   Ali
102  Sara
103  Reza

     salary
101    3000
102    4000
104    3500

In [18]:
result = pd.merge(
    employees,
    salaries,
    left_index=True,
    right_index=True,
    how='outer'
)

In [19]:
display(result)

     name  salary
101   Ali  3000.0
102  Sara  4000.0
103  Reza     NaN
104   NaN  3500.0

Key arguments recap :
Argument	        What it matches
on	                Same-named columns
left_on	            Named column(s) on left
right_on	        Named column(s) on right
left_index=True	    Left DataFrame's index
right_index=True	Right DataFrame's index

#Mini project: Customer and transaction analysis
Business scenario
You work for an online store. Two departments provide data:
- The CRM department provides customer information.
- The finance department provides transaction information.
Unfortunately, they use different column names for customer IDs.
Your task is to combine their data and calculate how much each customer has spent.

In [20]:
#Create the datasets
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "customer_name": [
        "Ali", "Sara", "Reza", "Mina", "Hassan"
    ],
    "city": [
        "Tehran", "Shiraz", "Isfahan", "Tabriz", "Mashhad"
    ]
})

transactions = pd.DataFrame({
    "transaction_id": [1, 2, 3, 4, 5, 6],
    "client_id": [101, 101, 102, 103, 103, 106],
    "amount": [500, 300, 750, 200, 400, 900]
})

display(customers)
display(transactions)

   customer_id customer_name     city
0          101           Ali   Tehran
1          102          Sara   Shiraz
2          103          Reza  Isfahan
3          104          Mina   Tabriz
4          105        Hassan  Mashhad

   transaction_id  client_id  amount
0               1        101     500
1               2        101     300
2               3        102     750
3               4        103     200
4               5        103     400
5               6        106     900

In [33]:
#Merge using different key names
result = pd.merge(
    customers,
    transactions,
    left_on='customer_id',
    right_on='client_id',
    how='left'
)
display(result)

   customer_id customer_name     city  transaction_id  client_id  amount
0          101           Ali   Tehran             1.0      101.0   500.0
1          101           Ali   Tehran             2.0      101.0   300.0
2          102          Sara   Shiraz             3.0      102.0   750.0
3          103          Reza  Isfahan             4.0      103.0   200.0
4          103          Reza  Isfahan             5.0      103.0   400.0
5          104          Mina   Tabriz             NaN        NaN     NaN
6          105        Hassan  Mashhad             NaN        NaN     NaN

In [34]:
#Calculate total spending
result = result.drop(columns='client_id')
result_total = result.groupby(['customer_id','customer_name','city']).agg(
    total_amount = ('amount','sum'),
    order_counts = ('transaction_id','count')
)
display(result_total)

                                   total_amount  order_counts
customer_id customer_name city
101         Ali           Tehran          800.0             2
102         Sara          Shiraz          750.0             1
103         Reza          Isfahan         600.0             2
104         Mina          Tabriz            0.0             0
105         Hassan        Mashhad           0.0             0

In [35]:
#Find customers with no transactions
result_total.loc[result_total['order_counts'] == 0]

                                   total_amount  order_counts
customer_id customer_name city
104         Mina          Tabriz            0.0             0
105         Hassan        Mashhad           0.0             0

In [36]:
#Investigate unmatched transactions
audit = pd.merge(
    customers,
    transactions,
    left_on = 'customer_id',
    right_on = 'client_id',
    how = 'outer',
    indicator = True
)
display(audit)

,customer_id,customer_name,city,transaction_id,client_id,amount,_merge
0,101.0,Ali,Tehran,1.0,101.0,500.0,both
1,101.0,Ali,Tehran,2.0,101.0,300.0,both
2,102.0,Sara,Shiraz,3.0,102.0,750.0,both
3,103.0,Reza,Isfahan,4.0,103.0,200.0,both
4,103.0,Reza,Isfahan,5.0,103.0,400.0,both
5,104.0,Mina,Tabriz,NaN,NaN,NaN,left_only
6,105.0,Hassan,Mashhad,NaN,NaN,NaN,left_only
7,NaN,NaN,NaN,6.0,106.0,900.0,right_only

In [37]:
#Find unmatched transactions:
audit.loc[audit['_merge'] == 'right_only']

,customer_id,customer_name,city,transaction_id,client_id,amount,_merge
7,NaN,NaN,NaN,6.0,106.0,900.0,right_only