In [1]:
#core concept
import pandas as pd

employees = pd.DataFrame({
    "name": [
        "Ali", "Sara", "Reza", "Maryam",
        "Hassan", "Neda", "Omid", "Zahra"
    ],
    "department": [
        "Data", "Web", "Data", "Backend",
        "Web", "Data", "Backend", "Web"
    ],
    "age": [25, 31, 28, 35, 24, 29, 32, 27],
    "salary": [2500, 3200, 2800, 4100, 2300, 3500, 3900, 3000],
    "experience": [2, 5, 3, 8, 1, 6, 7, 4],
    "performance": [82, 91, 76, 95, 68, 88, 93, 85]
})

employees

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93
7   Zahra        Web   27    3000           4           85

In [2]:
#Boolean filtering
employees[employees['salary']>3000]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93

DataFrame
   ↓
Condition
   ↓
True / False
   ↓
Keep True rows

Comparison operator :
>      # greater than
<      # less than
>=     # greater than or equal
<=     # less than or equal
==     # equal
!=     # not equal

In [5]:
#AND, OR, Not
#&, |, ~
#Find employees who: work in Data AND earn at least 3000
employees.loc[(employees['department']=='Data') & (employees['salary']>=3000)]

   name department  age  salary  experience  performance
5  Neda       Data   29    3500           6           88

In [6]:
# Find employees who: work in Data OR earn more than 4000
employees.loc[(employees['department']=='Data') | (employees['salary']>4000)]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88

In [7]:
# Find everyone who is NOT in Data:
employees.loc[~(employees['department']=='Data')]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
6    Omid    Backend   32    3900           7           93
7   Zahra        Web   27    3000           4           85

In [10]:
#Practice 1
#1-Employees with: age >= 30 AND performance >= 90
employees.loc[(employees['age'] >= 30) & (employees['performance'] >= 90)]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93

In [11]:
#2-Employees with: salary < 3000 OR performance < 75
employees.loc[(employees['salary'] < 3000) | (employees['performance'] < 75)]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
4  Hassan        Web   24    2300           1           68

In [12]:
#3-Employees who are not in Backend.
employees.loc[~(employees['department']=='Backend')]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
2    Reza       Data   28    2800           3           76
4  Hassan        Web   24    2300           1           68
5    Neda       Data   29    3500           6           88
7   Zahra        Web   27    3000           4           85

In [13]:
#Professional Filtering with .loc
employees.loc[employees['age']>30,['name','age']]

     name  age
1    Sara   31
3  Maryam   35
6    Omid   32

df.loc[
    CONDITION,
    COLUMNS
]

In [21]:
#isin
#Suppose you want employees from either: Data, Backend
employees.loc[(employees['department'] == 'Data') | (employees['department'] == 'Backend')]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93

In [22]:
#Intead of code above we can use isin()
employees.loc[employees['department'].isin(['Data','Backend'])]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93

In [23]:
#another example
employees.loc[employees['name'].isin(['Ali','Omid'])]

   name department  age  salary  experience  performance
0   Ali       Data   25    2500           2           82
6  Omid    Backend   32    3900           7           93

In [25]:
#between
#Suppose we want employees between 25 and 30 years old.
employees.loc[(employees['age'] >= 25) & (employees['age'] <= 30)]

    name department  age  salary  experience  performance
0    Ali       Data   25    2500           2           82
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

In [27]:
#Intead of code above we can use between()
employees.loc[employees['age'].between(25,30)]

    name department  age  salary  experience  performance
0    Ali       Data   25    2500           2           82
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

In [28]:
#By default, between() includes both endpoints.

#string filtering
Real datasets contain a LOT of text.
Pandas gives us .str

In [29]:
#Names starting with "A"
employees.loc[employees['name'].str.startswith('A')]

  name department  age  salary  experience  performance
0  Ali       Data   25    2500           2           82

In [30]:
#Names ending with "a"
employees.loc[employees['name'].str.endswith('a')]

    name department  age  salary  experience  performance
1   Sara        Web   31    3200           5           91
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

Case-insensitive search
Suppose the data contains:
Data
data
DATA
You can do:

In [32]:
employees.loc[employees['department'].str.contains('data', case=False, na=False)]

   name department  age  salary  experience  performance
0   Ali       Data   25    2500           2           82
2  Reza       Data   28    2800           3           76
5  Neda       Data   29    3500           6           88

case=False means case doesn't matter.
na=False is useful when the column contains missing values.

In [33]:
#missing values
employees.loc[2, "salary"] = None
employees.loc[5, "performance"] = None

In [34]:
employees

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
1    Sara        Web   31  3200.0           5         91.0
2    Reza       Data   28     NaN           3         76.0
3  Maryam    Backend   35  4100.0           8         95.0
4  Hassan        Web   24  2300.0           1         68.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0
7   Zahra        Web   27  3000.0           4         85.0

In [35]:
#Find rows where salary is missing
employees.loc[employees['salary'].isna()]

   name department  age  salary  experience  performance
2  Reza       Data   28     NaN           3         76.0

In [36]:
#Find rows where salary is NOT missing
employees.loc[employees['salary'].notna()]

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
1    Sara        Web   31  3200.0           5         91.0
3  Maryam    Backend   35  4100.0           8         95.0
4  Hassan        Web   24  2300.0           1         68.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0
7   Zahra        Web   27  3000.0           4         85.0

Don't do this:
employees["salary"] == None

For Pandas missing-value detection, prefer:
.isna()
.notna()

query() : Pandas has another elegant filtering syntax

In [38]:
employees.query('salary > 3000')

     name department  age  salary  experience  performance
1    Sara        Web   31  3200.0           5         91.0
3  Maryam    Backend   35  4100.0           8         95.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0

In [39]:
#multiple conditions
employees.query('salary > 3000 and age > 30')

     name department  age  salary  experience  performance
1    Sara        Web   31  3200.0           5         91.0
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0

In [40]:
#age range
employees.query(' 25 < age < 30')

    name department  age  salary  experience  performance
2   Reza       Data   28     NaN           3         76.0
5   Neda       Data   29  3500.0           6          NaN
7  Zahra        Web   27  3000.0           4         85.0

For complex Pandas code, Boolean expressions with .loc are often more explicit. 
query() can be very readable for straightforward conditions.

In [43]:
#Filtering + Sorting + Selecting
#Find Data employees with performance >= 80, show their name, salary and performance, and sort them from highest performance to lowest.
employees.loc[(employees['performance'] >= 80) & (employees['department']=='Data'),['name','salary','performance']].sort_values(by='performance',ascending=False)

  name  salary  performance
0  Ali  2500.0         82.0

In [44]:
#challenge
#Find employees in:
#Data OR Backend
#using .isin().
employees.loc[employees['department'].isin(['Data','Backend'])]

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
2    Reza       Data   28     NaN           3         76.0
3  Maryam    Backend   35  4100.0           8         95.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0

In [45]:
#Challenge 4
#Find employees whose age is between 25 and 32.
employees.loc[employees['age'].between(25,32)]

    name department  age  salary  experience  performance
0    Ali       Data   25  2500.0           2         82.0
1   Sara        Web   31  3200.0           5         91.0
2   Reza       Data   28     NaN           3         76.0
5   Neda       Data   29  3500.0           6          NaN
6   Omid    Backend   32  3900.0           7         93.0
7  Zahra        Web   27  3000.0           4         85.0

In [46]:
#Find employees whose name contains "a" regardless of capitalization.
employees.loc[employees['name'].str.contains('a',case=False)]

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
1    Sara        Web   31  3200.0           5         91.0
2    Reza       Data   28     NaN           3         76.0
3  Maryam    Backend   35  4100.0           8         95.0
4  Hassan        Web   24  2300.0           1         68.0
5    Neda       Data   29  3500.0           6          NaN
7   Zahra        Web   27  3000.0           4         85.0

In [48]:
#Create a professional analysis:
#Find employees who are in the Data department, 
#have at least 3 years of experience, 
#and have performance >= 80. 
#Show only their name, salary, experience and performance, 
#then sort them by performance from highest to lowest.
employees.loc[(employees['department']=='Data') & (employees['experience'] >= 3),['name','salary','experience','performance']].sort_values('performance',ascending=False)

   name  salary  experience  performance
2  Reza     NaN           3         76.0
5  Neda  3500.0           6          NaN

#Cheat Sheet
# Basic
df[df["salary"] > 3000]

# Comparison
df[df["age"] >= 30]

# AND
df[
    (df["age"] >= 30) &
    (df["salary"] > 3000)
]

# OR
df[
    (df["department"] == "Data") |
    (df["department"] == "Web")
]

# NOT
df[
    ~(df["department"] == "Data")
]

# loc + condition + columns
df.loc[
    df["salary"] > 3000,
    ["name", "salary"]
]

# isin
df[
    df["department"].isin(
        ["Data", "Backend"]
    )
]

# NOT isin
df[
    ~df["department"].isin(
        ["Data", "Backend"]
    )
]

# between
df[
    df["age"].between(25, 30)
]

# string contains
df[
    df["name"].str.contains(
        "a",
        case=False,
        na=False
    )
]

# startswith
df[
    df["name"].str.startswith("A")
]

# endswith
df[
    df["name"].str.endswith("a")
]

# Missing values
df[df["salary"].isna()]

# Non-missing
df[df["salary"].notna()]

# query
df.query("salary > 3000")

# query + multiple conditions
df.query(
    "salary > 3000 and performance >= 90"
)

# Filter + select + sort
df.loc[
    condition,
    ["col1", "col2"]
].sort_values(
    "col1",
    ascending=False
)