In [1]:
import pandas as pd
students = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza", "Maryam", "Hassan", "Neda"],
    "age": [22, 24, 21, 23, 25, 22],
    "math": [85, 92, 70, 96, 60, 88],
    "python": [90, 95, 65, 98, 75, 84],
    "statistics": [78, 89, 72, 94, 64, 90]
})
print(students)

     name  age  math  python  statistics
0     Ali   22    85      90          78
1    Sara   24    92      95          89
2    Reza   21    70      65          72
3  Maryam   23    96      98          94
4  Hassan   25    60      75          64
5    Neda   22    88      84          90

Filtering means:
"Show me only the rows that satisfy a condition."

In [4]:
#filter based on python scores
students.loc[students['math'] >= 85]

     name  age  math  python  statistics
0     Ali   22    85      90          78
1    Sara   24    92      95          89
3  Maryam   23    96      98          94
5    Neda   22    88      84          90

In [6]:
#practice 1
#Find students whose python score is greater than 90
students.loc[students['python'] > 90]

     name  age  math  python  statistics
1    Sara   24    92      95          89
3  Maryam   23    96      98          94

In [7]:
#Multiple conditions : () & |
students.loc[(students['math'] > 85) & (students['python'] > 90)]

     name  age  math  python  statistics
1    Sara   24    92      95          89
3  Maryam   23    96      98          94

In [10]:
students.loc[(students['statistics'] > 90) | (students['math'] > 90)]

     name  age  math  python  statistics
1    Sara   24    92      95          89
3  Maryam   23    96      98          94

In [11]:
#Practice 2
#Find students who are: age <= 22 AND python >= 80
students.loc[(students['age'] <= 22) & (students['python'] >= 80)]

   name  age  math  python  statistics
0   Ali   22    85      90          78
5  Neda   22    88      84          90

Filtering asks:
    Which rows do I want?
Sorting asks:
    In what order do I want them?

In [12]:
#Sorting
students.sort_values(by='python')

     name  age  math  python  statistics
2    Reza   21    70      65          72
4  Hassan   25    60      75          64
5    Neda   22    88      84          90
0     Ali   22    85      90          78
1    Sara   24    92      95          89
3  Maryam   23    96      98          94

In [13]:
#descending sort
students.sort_values(by='python', ascending=False)

     name  age  math  python  statistics
3  Maryam   23    96      98          94
1    Sara   24    92      95          89
0     Ali   22    85      90          78
5    Neda   22    88      84          90
4  Hassan   25    60      75          64
2    Reza   21    70      65          72

In [14]:
#Practice 3
#Sort students by age from youngest to oldest.
students.sort_values(by='age')

     name  age  math  python  statistics
2    Reza   21    70      65          72
0     Ali   22    85      90          78
5    Neda   22    88      84          90
3  Maryam   23    96      98          94
1    Sara   24    92      95          89
4  Hassan   25    60      75          64

In [16]:
#Sorting by Multiple Columns
students.sort_values(by=['python','math'],ascending=[False,False])

     name  age  math  python  statistics
3  Maryam   23    96      98          94
1    Sara   24    92      95          89
0     Ali   22    85      90          78
5    Neda   22    88      84          90
4  Hassan   25    60      75          64
2    Reza   21    70      65          72

In [18]:
#Filtering + Sorting
#Find students with Python >= 80 and sort them by Python score
students.loc[students['python'] >= 80].sort_values(by='python')

     name  age  math  python  statistics
5    Neda   22    88      84          90
0     Ali   22    85      90          78
1    Sara   24    92      95          89
3  Maryam   23    96      98          94

In [19]:
#Selecting specific columns 
students.loc[students['python'] >= 80, ['name','python']].sort_values(by='python')

     name  python
5    Neda      84
0     Ali      90
1    Sara      95
3  Maryam      98

In [21]:
#Final mini project
#Task 1
#Find students whose average performance is not directly available yet.
students['average'] = (students['math'] + students['python'] + students['statistics']) / 3
students["average"] = students["average"].round(2)
students

     name  age  math  python  statistics  average
0     Ali   22    85      90          78    84.33
1    Sara   24    92      95          89    92.00
2    Reza   21    70      65          72    69.00
3  Maryam   23    96      98          94    96.00
4  Hassan   25    60      75          64    66.33
5    Neda   22    88      84          90    87.33

In [22]:
#Task 2
#Show students with an average score of 85 or higher.
students.loc[students['average'] >= 85]

     name  age  math  python  statistics  average
1    Sara   24    92      95          89    92.00
3  Maryam   23    96      98          94    96.00
5    Neda   22    88      84          90    87.33

In [24]:
#Task 3
#Show the top 3 students based on average score.
students_byaverage = students.sort_values(by='average', ascending=False)
students_byaverage.head(3)

     name  age  math  python  statistics  average
3  Maryam   23    96      98          94    96.00
1    Sara   24    92      95          89    92.00
5    Neda   22    88      84          90    87.33

In [29]:
#Task 4 
#Show only: name, python, average
#for students with: python >= 85 AND average >= 85
#Sort them from highest average to lowest.
new_list = students.loc[(students['python'] >= 85) & (students['average'] >= 85), ['name','python','average']]
new_list.sort_values(by='average', ascending=False)

     name  python  average
3  Maryam      98     96.0
1    Sara      95     92.0