In [1]:
#Create Dataset
import pandas as pd

sales = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Monitor", "Keyboard"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara", "Ali", "Neda"
    ],
    "region": [
        "North", "South", "West", "East",
        "North", "East", "South", "West",
        "North", "South", "East", "West"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12, 4, 6],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25, 400, 50]
})

sales["revenue"] = sales["quantity"] * sales["price"]

In [2]:
#With one column: How much revenue did each product generate?
sales.groupby("product")["revenue"].sum()

product
Keyboard     950
Laptop      5000
Monitor     3600
Mouse        925
Name: revenue, dtype: int64

In [4]:
#With two columns: How much revenue did each product generate within each region?
sales.groupby(['region','product'],as_index=False)['revenue'].sum()

  region   product  revenue
0   East    Laptop     1000
1   East   Monitor     1600
2   East     Mouse      375
3  North    Laptop     4000
4  North   Monitor     1200
5  South  Keyboard      400
6  South     Mouse      550
7   West  Keyboard      550
8   West   Monitor      800

In [6]:
#Multiple aggregations
#For every region/product combination, show total revenue, total quantity, average order revenue, and number of orders.
sales.groupby(['region','product'],as_index=False).agg(
    total_revenue = ('revenue','sum'),
    total_quantity = ('quantity','sum'),
    average_revenue = ('revenue','mean'),
    number_od_order = ('order_id','count')
)

,region,product,total_revenue,total_quantity,average_revenue,number_od_order
0,East,Laptop,1000,1,1000.0,1
1,East,Monitor,1600,4,1600.0,1
2,East,Mouse,375,15,375.0,1
3,North,Laptop,4000,4,2000.0,2
4,North,Monitor,1200,3,1200.0,1
5,South,Keyboard,400,8,400.0,1
6,South,Mouse,550,22,275.0,2
7,West,Keyboard,550,11,275.0,2
8,West,Monitor,800,2,800.0,1

In [7]:
#Sort it
sales.groupby(['region','product'],as_index=False).agg(
    total_revenue = ('revenue','sum'),
    total_quantity = ('quantity','sum'),
    average_revenue = ('revenue','mean'),
    number_od_order = ('order_id','count')
).sort_values(by='total_revenue',ascending=False)

,region,product,total_revenue,total_quantity,average_revenue,number_od_order
3,North,Laptop,4000,4,2000.0,2
1,East,Monitor,1600,4,1600.0,1
4,North,Monitor,1200,3,1200.0,1
0,East,Laptop,1000,1,1000.0,1
8,West,Monitor,800,2,800.0,1
7,West,Keyboard,550,11,275.0,2
6,South,Mouse,550,22,275.0,2
5,South,Keyboard,400,8,400.0,1
2,East,Mouse,375,15,375.0,1

In [9]:
#Three-column groupby()
sales.groupby(
    ["region", "category", "product"], as_index=False
).agg(
    total_revenue = ('revenue','sum'),
    total_quantity = ('quantity','sum')
)

  region     category   product  total_revenue  total_quantity
0   East  Accessories     Mouse            375              15
1   East  Electronics    Laptop           1000               1
2   East  Electronics   Monitor           1600               4
3  North  Electronics    Laptop           4000               4
4  North  Electronics   Monitor           1200               3
5  South  Accessories  Keyboard            400               8
6  South  Accessories     Mouse            550              22
7   West  Accessories  Keyboard            550              11
8   West  Electronics   Monitor            800               2

In [11]:
#Filter + Multiple groupby()
#For the North and East regions, show the performance of each salesperson for each product.
sales.loc[sales['region'].isin(['North','East'])].groupby(['product','salesperson'],as_index=False).agg(
    total_revenue=('revenue','sum'),
    total_quantity=('quantity','sum')
)

   product salesperson  total_revenue  total_quantity
0   Laptop         Ali           2000               2
1   Laptop        Reza           3000               3
2  Monitor         Ali           1600               4
3  Monitor        Sara           1200               3
4    Mouse         Ali            375              15