In [1]:
#Aggregation → What does the data tell us overall?

In [2]:
import pandas as pd
#create our data set
sales = pd.DataFrame({
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25]
})

sales

    product     category salesperson  quantity  price
0    Laptop  Electronics         Ali         2   1000
1     Mouse  Accessories        Sara        10     25
2  Keyboard  Accessories         Ali         5     50
3    Laptop  Electronics        Reza         1   1000
4   Monitor  Electronics        Sara         3    400
5     Mouse  Accessories         Ali        15     25
6  Keyboard  Accessories        Reza         8     50
7   Monitor  Electronics        Sara         2    400
8    Laptop  Electronics        Reza         2   1000
9     Mouse  Accessories        Sara        12     25

In [3]:
#calculate revenue
sales['revenue'] = sales['quantity'] * sales['price']
sales

    product     category salesperson  quantity  price  revenue
0    Laptop  Electronics         Ali         2   1000     2000
1     Mouse  Accessories        Sara        10     25      250
2  Keyboard  Accessories         Ali         5     50      250
3    Laptop  Electronics        Reza         1   1000     1000
4   Monitor  Electronics        Sara         3    400     1200
5     Mouse  Accessories         Ali        15     25      375
6  Keyboard  Accessories        Reza         8     50      400
7   Monitor  Electronics        Sara         2    400      800
8    Laptop  Electronics        Reza         2   1000     2000
9     Mouse  Accessories        Sara        12     25      300

In [4]:
#Aggregation means taking many values and producing a summary value.

In [6]:
#Basic aggregation functions
#sum = total
sales['revenue'].sum()

np.int64(8575)

In [7]:
#mean = average
sales['revenue'].mean()

np.float64(857.5)

In [8]:
#median = middle value after sorting
sales['revenue'].median()

np.float64(600.0)

In [9]:
#min = smallest value
sales['revenue'].min()

np.int64(250)

In [10]:
#max = largest value
sales['revenue'].max()

np.int64(2000)

In [11]:
#count = number of non missing value
sales['revenue'].count()

np.int64(10)

In [14]:
#nunique = number of unique values
sales['product'].nunique()

4

In [15]:
#unique = return unique values
sales['product'].unique()

<StringArray>
['Laptop', 'Mouse', 'Keyboard', 'Monitor']
Length: 4, dtype: str

In [16]:
#practice 1
#Find total revenue.
print(sales['revenue'].sum())
#Find average quantity per transaction.
print(sales['quantity'].mean())
#Find the largest transaction revenue.
print(sales['revenue'].max())
#How many unique products are there?
print(sales['product'].nunique())
#How many unique salespeople?
print(sales['salesperson'].nunique())

8575
6.0
2000
4
3

In [17]:
#Aggregating Multiple Columns
sales[['quantity','price','revenue']].mean()

quantity      6.0
price       397.5
revenue     857.5
dtype: float64

In [18]:
#Different aggregations for different columns
#agg()
sales.agg({
    "quantity":"sum",
    "price":"mean",
    "revenue":"max"
})

quantity      60.0
price        397.5
revenue     2000.0
dtype: float64

In [19]:
#Master agg()
#Apply one or more aggregation functions.
#One column, multiple aggregations
sales['revenue'].agg(['max','min','sum','mean'])

max     2000.0
min      250.0
sum     8575.0
mean     857.5
Name: revenue, dtype: float64

In [20]:
#Multiple columns, multiple functions
sales[['quantity','revenue']].agg(['sum','mean','median'])

        quantity  revenue
sum         60.0   8575.0
mean         6.0    857.5
median       4.0    600.0

In [21]:
#Different functions for different columns
sales.agg({
    "quantity":["sum","median"],
    "revenue":['max','min','mean'],
    "price":["count"]
})

        quantity  revenue  price
sum         60.0      NaN    NaN
median       4.0      NaN    NaN
max          NaN   2000.0    NaN
min          NaN    250.0    NaN
mean         NaN    857.5    NaN
count        NaN      NaN   10.0

In [22]:
#practice 2
#"Give me the total quantity sold, average price, and total revenue."
sales.agg({
    'quantity':['sum'],
    'price':['mean'],
    'revenue':['sum']
})

      quantity  price  revenue
sum       60.0    NaN   8575.0
mean       NaN  397.5      NaN

In [24]:
#Aggregation + Filtering
#Total revenue from Laptops
sales.loc[sales['product']=='Laptop','revenue'].sum()

np.int64(5000)

In [25]:
#Average revenue for Electronics
sales.loc[sales['category']=='Electronics','revenue'].mean()

np.float64(1400.0)

In [26]:
#Total quantity sold by Sara
sales.loc[sales['salesperson']=='Sara','quantity'].sum()

np.int64(27)

In [28]:
#Total revenue generated by Sara from Electronics:
sales.loc[(sales['category']=='Electronics') & (sales['salesperson']=='Sara'),'revenue'].sum()

np.int64(2000)

In [29]:
#Final Challenge
#Calculate:Total revenue
sales['revenue'].sum()

np.int64(8575)

In [30]:
#Average revenue per transaction
sales['revenue'].mean()

np.float64(857.5)

In [41]:
#Total quantity sold for each salesperson
sales.groupby('salesperson')['quantity'].sum()

salesperson
Ali     22
Reza    11
Sara    27
Name: quantity, dtype: int64

In [38]:
#Total revenue generated by the Electronics category.
sales.loc[sales['category']=='Electronics','revenue'].sum()

np.int64(7000)

In [39]:
#The maximum revenue transaction made by Sara.
sales.loc[sales['salesperson']=='Sara','revenue'].max()

np.int64(1200)

In [40]:
#Produce one summary containing:
#quantity → total and average
#price    → minimum and maximum
#revenue  → total, average, and maximum
sales.agg({
    "quantity":["sum","mean"],
    "price":["min","max"],
    "revenue":["sum","mean","max"]
})

      quantity   price  revenue
sum       60.0     NaN   8575.0
mean       6.0     NaN    857.5
min        NaN    25.0      NaN
max        NaN  1000.0   2000.0

#Day 25 Cheat Sheet
# Basic aggregation
df["column"].sum()
df["column"].mean()
df["column"].median()
df["column"].min()
df["column"].max()
df["column"].count()
df["column"].nunique()
df["column"].unique()

# Multiple columns
df[["col1", "col2"]].mean()
df[["col1", "col2"]].sum()

# Multiple functions
df["column"].agg([
    "sum",
    "mean",
    "min",
    "max"
])

# Different aggregation per column
df.agg({
    "quantity": "sum",
    "price": "mean",
    "revenue": "max"
})

# Multiple functions per column
df.agg({
    "quantity": ["sum", "mean"],
    "price": ["min", "max"],
    "revenue": ["sum", "mean", "max"]
})

# Filter + aggregate
df.loc[
    df["category"] == "Electronics",
    "revenue"
].sum()

# Multiple conditions + aggregate
df.loc[
    (df["category"] == "Electronics") &
    (df["salesperson"] == "Sara"),
    "revenue"
].sum()