missing values refers to values that is not exist in our dataframe and they're shown with NaN.
In data analysis, missing values can appear for many reasons:
1- Customer didn't provide the information
2- Data wasn't collected
3- Database error
4- Different systems use different formats
5- Information simply doesn't exist

In [1]:
import pandas as pd

data = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza", "Neda"],
    "age": [25, 30, None, 28],
    "salary": [1200, None, 1500, 1800]
})

data

   name   age  salary
0   Ali  25.0  1200.0
1  Sara  30.0     NaN
2  Reza   NaN  1500.0
3  Neda  28.0  1800.0

Here Sara's Salary and Reza's age are missing Value

NaN means: Not a Number / missing value

we should investigate missing data before deciding what to do with it.

In [2]:
#detect missing values
# isna() and isnull() : They are effectively equivalent.
data.isna()

    name    age  salary
0  False  False   False
1  False  False    True
2  False   True   False
3  False  False   False

Each True means:
There is a missing value here.

In [5]:
#Count Missing Values
#True is 1 and False is zero. so we can use agg functions to get information about NaN.
data.isna().sum()

name      0
age       1
salary    1
dtype: int64

Whenever you receive a new dataset, one of the first things you should do is: data.insna().sum()

In [6]:
#Missing percentage
data.isna().mean()*100

name       0.0
age       25.0
salary    25.0
dtype: float64

here True is 1 and False is zero. so we multiple mean 100 to calculate percentage of NaN.

In [7]:
#Finding Rows With Missing Values
data.loc[data['age'].isna()]

   name  age  salary
2  Reza  NaN  1500.0

In [8]:
#Find rows where salary is missing
data.loc[data['salary'].isna()]

   name   age  salary
1  Sara  30.0     NaN

In [13]:
#Find rows with missing values anywhere
data.loc[data.isna().any(axis=1)]

   name   age  salary
1  Sara  30.0     NaN
2  Reza   NaN  1500.0

.any(axis=1) --> means: Does this row contain at least one True

In [14]:
#Missing Values in the Real Dataset
df = pd.read_csv('supermart.csv')
df.head()

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu

In [15]:
df.isna().sum()

Order ID         0
Customer Name    0
Category         0
Sub Category     0
City             0
Order Date       0
Region           0
Sales            0
Discount         0
Profit           0
State            0
dtype: int64

In [16]:
df.isna().mean() * 100

Order ID         0.0
Customer Name    0.0
Category         0.0
Sub Category     0.0
City             0.0
Order Date       0.0
Region           0.0
Sales            0.0
Discount         0.0
Profit           0.0
State            0.0
dtype: float64

In [17]:
#practice 1
#create a new dataframe
practice = pd.DataFrame({
    "customer": ["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"],
    "age": [25, None, 31, 28, None, 35],
    "city": ["Tehran", "Shiraz", None, "Tabriz", "Tehran", None],
    "income": [1200, 1800, None, 1500, None, 2100]
})

practice

  customer   age    city  income
0      Ali  25.0  Tehran  1200.0
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None     NaN
3     Neda  28.0  Tabriz  1500.0
4   Hassan   NaN  Tehran     NaN
5   Maryam  35.0    None  2100.0

In [18]:
#How many missing values are there in each column?
practice.isna().sum()

customer    0
age         2
city        2
income      2
dtype: int64

In [19]:
#Which rows have at least one missing value?
practice.loc[practice.isna().any(axis=1)]

  customer   age    city  income
1     Sara   NaN  Shiraz  1800.0
2     Reza  31.0    None     NaN
4   Hassan   NaN  Tehran     NaN
5   Maryam  35.0    None  2100.0

In [21]:
#How many missing values are there in the entire DataFrame?
practice.isna().sum().sum()

np.int64(6)

In [24]:
#Calculate the missing percentage for every column and sort it from highest to lowest.
average_result = practice.isna().mean() * 100
average_result.sort_values(ascending=False)

age         33.333333
city        33.333333
income      33.333333
customer     0.000000
dtype: float64

In [27]:
#Find age whose income is missing.
practice.loc[practice['age'].isna()]

  customer  age    city  income
1     Sara  NaN  Shiraz  1800.0
4   Hassan  NaN  Tehran     NaN

#Summary
Detect : df.isna()
Count by column : df.isna().sum()
Total missing : df.isna().sum().sum()
Find rows with missing values : df.loc[df.isna().any(axis=1)]
Missing percentage : df.isna().mean() * 100
Most important principle: Detect first. Understand second. Clean third.