In [11]:
import pandas as pd
students = pd.read_csv("./students.csv")

In [16]:
#Check dataframe
students.head()

     name  age  math  python  statistics
0     Ali   22    85      90          78
1    Sara   24    92      95          89
2    Reza   21    70      65          72
3  Maryam   23    96      98          94
4  Hassan   25    60      75          64

In [19]:
#check the size and rows and columns of our dataframe
students.shape

(6, 5)

In [21]:
#check information of our dataframe
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6 non-null      object
 1   age         6 non-null      int64
 2   math        6 non-null      int64
 3   python      6 non-null      int64
 4   statistics  6 non-null      int64
dtypes: int64(4), object(1)
memory usage: 372.0+ bytes

In [23]:
#check last rows of dataframe
students.tail(2)

     name  age  math  python  statistics
4  Hassan   25    60      75          64
5    Neda   22    88      84          90

In [24]:
#check columns of our dataframe
students.columns

Index(['name', 'age', 'math', 'python', 'statistics'], dtype='object')

In [25]:
#check data types of our dataframe
students.dtypes

name          object
age            int64
math           int64
python         int64
statistics     int64
dtype: object

In [26]:
#check statistical status of our dataframe
students.describe()

             age       math     python  statistics
count   6.000000   6.000000   6.000000    6.000000
mean   22.833333  81.833333  84.500000   81.166667
std     1.471960  13.920010  12.597619   11.771434
min    21.000000  60.000000  65.000000   64.000000
25%    22.000000  73.750000  77.250000   73.500000
50%    22.500000  86.500000  87.000000   83.500000
75%    23.750000  91.000000  93.750000   89.750000
max    25.000000  96.000000  98.000000   94.000000

In [27]:
#Highest math score
students['math'].max()

96

In [28]:
#Lowest pyhton score
students['python'].min()

65

In [29]:
#Average statistics scores
students['statistics'].mean()

np.float64(81.16666666666667)

In [30]:
#create average column
students['average'] = ((students['math'] + students['python'] + students['statistics']) / 3).round(2)
students.head(3)

   name  age  math  python  statistics  average
0   Ali   22    85      90          78    84.33
1  Sara   24    92      95          89    92.00
2  Reza   21    70      65          72    69.00

In [31]:
#Question 1
#Who scored 90 or higher in Python?
students.loc[students['python'] >= 90]

     name  age  math  python  statistics  average
0     Ali   22    85      90          78    84.33
1    Sara   24    92      95          89    92.00
3  Maryam   23    96      98          94    96.00

In [32]:
#Question 2
#Who has an average >= 85?
students.loc[students['average'] >= 85]

     name  age  math  python  statistics  average
1    Sara   24    92      95          89    92.00
3  Maryam   23    96      98          94    96.00
5    Neda   22    88      84          90    87.33

In [33]:
#Question 3
#Who has Math >= 85 AND Python >= 85?
students.loc[(students['math'] >= 85) & (students['python'] >= 85)]

     name  age  math  python  statistics  average
0     Ali   22    85      90          78    84.33
1    Sara   24    92      95          89    92.00
3  Maryam   23    96      98          94    96.00

In [34]:
#Question 4 
#Show only: name, python, average for students whose average is at least 85.
students.loc[students['average'] >= 85, ['name', 'python', 'average']]

     name  python  average
1    Sara      95    92.00
3  Maryam      98    96.00
5    Neda      84    87.33

In [35]:
#create ranking
ranking = students.sort_values(by='average', ascending = False)

In [36]:
ranking

     name  age  math  python  statistics  average
3  Maryam   23    96      98          94    96.00
1    Sara   24    92      95          89    92.00
5    Neda   22    88      84          90    87.33
0     Ali   22    85      90          78    84.33
2    Reza   21    70      65          72    69.00
4  Hassan   25    60      75          64    66.33

In [37]:
#find top students
top_student_index = students['average'].idxmax()
students.loc[top_student_index]

name          Maryam
age               23
math              96
python            98
statistics        94
average         96.0
Name: 3, dtype: object

In [38]:
#Answer Real Analysis Questions
#Question 1 — What is the average performance of the whole class?
students['average'].mean()

np.float64(82.49833333333332)

In [42]:
#Question 2 — Subject performance
#What's the average score for each subject?
print(students[['math','python','statistics']].mean())

math          81.833333
python        84.500000
statistics    81.166667
dtype: float64

In [44]:
#Question 3 — Students needing attention
#Let's define a student as needing attention if they scored below 70 in any subject.
students.loc[(students['python'] < 70) | (students['math'] < 70) | (students['statistics'] < 70)]

     name  age  math  python  statistics  average
2    Reza   21    70      65          72    69.00
4  Hassan   25    60      75          64    66.33

In [45]:
#export analysis
ranking.to_csv('result.csv', index=False)

In [46]:
#Start Day 21 - Complete project
#create status columns
students['status'] = students['average'].apply(lambda avg: 'Passed' if avg> 70 else 'Not passed')
students

     name  age  math  python  statistics  average      status
0     Ali   22    85      90          78    84.33      Passed
1    Sara   24    92      95          89    92.00      Passed
2    Reza   21    70      65          72    69.00  Not passed
3  Maryam   23    96      98          94    96.00      Passed
4  Hassan   25    60      75          64    66.33  Not passed
5    Neda   22    88      84          90    87.33      Passed

In [48]:
#print unique values
print(students['status'].value_counts())

status
Passed        4
Not passed    2
Name: count, dtype: int64

In [50]:
#create subjects avearge 
subject = ['math','python','statistics']
subject_average = students[subject].mean()
subject_average

math          81.833333
python        84.500000
statistics    81.166667
dtype: float64

In [52]:
best_subject_id = subject_average.idxmax()
subject_average.loc[best_subject_id]

np.float64(84.5)