In [1]:
import pandas as pd

employees = pd.DataFrame({
    "name": [
        "Ali", "Sara", "Reza", "Maryam",
        "Hassan", "Neda", "Omid", "Zahra"
    ],
    "department": [
        "Data", "Web", "Data", "Backend",
        "Web", "Data", "Backend", "Web"
    ],
    "age": [25, 31, 28, 35, 24, 29, 32, 27],
    "salary": [2500, 3200, 2800, 4100, 2300, 3500, 3900, 3000],
    "experience": [2, 5, 3, 8, 1, 6, 7, 4],
    "performance": [82, 91, 76, 95, 68, 88, 93, 85]
})

employees

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93
7   Zahra        Web   27    3000           4           85

In [2]:
employees['salary'] > 3000

0    False
1     True
2    False
3     True
4    False
5     True
6     True
7    False
Name: salary, dtype: bool

In [3]:
employees.loc[employees['salary'] > 3000]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93

In [4]:
#AND, OR, NOT
#Employees with salary >= 3000 AND performance >= 90.
employees.loc[(employees['salary'] > 3000) & (employees['performance'] >= 90)]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93

In [5]:
#Salary >= 4000 OR performance >= 90.
employees[(employees['salary'] >= 4000) | (employees['performance'] >= 90)]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93

In [6]:
#Everyone who is NOT in Data.
employees[~(employees['department']=='Data')]

     name department  age  salary  experience  performance
1    Sara        Web   31    3200           5           91
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
6    Omid    Backend   32    3900           7           93
7   Zahra        Web   27    3000           4           85

In [7]:
#Put every individual condition inside parentheses.

In [8]:
#complex conditions
#Find Data employees who have at least 3 years of experience AND performance >= 80.
employees.loc[(employees['experience'] >= 3) & (employees['department']=='Data') & (employees['performance'] >= 80)]

   name department  age  salary  experience  performance
5  Neda       Data   29    3500           6           88

In [9]:
#AND + OR Together
#Find employees who are in Data AND either: performance >= 90 OR salary >= 4000
employees.loc[(employees['department']=='Data') & ((employees['performance'] >= 90) | (employees['salary'] >= 4000))]

Empty DataFrame
Columns: [name, department, age, salary, experience, performance]
Index: []

In [10]:
#Practice 1
#Find employees who are: Web OR Backend AND performance >= 85
employees.loc[(employees['department'].isin(['Data','Backend'])) & (employees['performance'] >= 85)]

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93

In [12]:
#between()
employees.loc[employees["age"].between(25,30)]

    name department  age  salary  experience  performance
0    Ali       Data   25    2500           2           82
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

In [13]:
#exclude boundaries
employees.loc[employees['age'].between(25,30,inclusive='neither')]

    name department  age  salary  experience  performance
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

In [18]:
#we can use inclusive="left" and inclusive="right"
employees.loc[employees['age'].between(25,29,inclusive='right')]

    name department  age  salary  experience  performance
2   Reza       Data   28    2800           3           76
5   Neda       Data   29    3500           6           88
7  Zahra        Web   27    3000           4           85

In [22]:
#Strings + Missing Values
#Find employees whose name contains "a"
employees.loc[employees['name'].str.contains('a',case=False,na=False)]

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
5    Neda       Data   29    3500           6           88
7   Zahra        Web   27    3000           4           85

In [23]:
#create missing values
employees.loc[2, "salary"] = None
employees.loc[5, "performance"] = None

In [24]:
employees

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
1    Sara        Web   31  3200.0           5         91.0
2    Reza       Data   28     NaN           3         76.0
3  Maryam    Backend   35  4100.0           8         95.0
4  Hassan        Web   24  2300.0           1         68.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0
7   Zahra        Web   27  3000.0           4         85.0

In [25]:
#Find employees with missing salary
employees.loc[employees['salary'].isna()]

   name department  age  salary  experience  performance
2  Reza       Data   28     NaN           3         76.0

In [28]:
#Employees whose salary is missing OR performance is below 75.
employees.loc[(employees['salary'].isna()) & (employees['performance'] < 75)]

Empty DataFrame
Columns: [name, department, age, salary, experience, performance]
Index: []

In [29]:
#Show the name, department, salary, and performance of Data or Backend employees who have at least 3 years of experience and performance >= 80.
employees.loc[(employees['department'].isin(['Data','Backend'])) & (employees['experience'] >= 3) & (employees['performance'] >= 80),['name','department','salary','performance']]

     name department  salary  performance
3  Maryam    Backend  4100.0         95.0
6    Omid    Backend  3900.0         93.0

In [30]:
#final challenge
#Find employees who:
#age between 25 and 32
#AND
#salary >= 3000
employees.loc[(employees['age'].between(25,32,inclusive='neither')) & (employees['salary'] >= 3000)]

    name department  age  salary  experience  performance
1   Sara        Web   31  3200.0           5         91.0
5   Neda       Data   29  3500.0           6          NaN
7  Zahra        Web   27  3000.0           4         85.0

I need a list of employees from the Data or Backend teams who have 2+ years of experience, performance of at least 80, and a salary between 2000 and 4000. Show me their name, department, salary, and performance, with the highest performers first.

In [36]:
employees.loc[
    (employees['department'].isin(['Data','Backend'])) &
    (employees['experience'] >= 2) &
    (employees['performance'] >= 80) &
    (employees['salary'].between(2000,4000)),
    ['name','department','salary','performance']
].sort_values(by='performance', ascending=False)

   name department  salary  performance
6  Omid    Backend  3900.0         93.0
0   Ali       Data  2500.0         82.0

# AND
(condition1) & (condition2)

# OR
(condition1) | (condition2)

# NOT
~(condition)

# Multiple AND
(condition1) & (condition2) & (condition3)

# AND + OR
(condition1) & (
    (condition2) | (condition3)
)

# Multiple allowed values
df["department"].isin(
    ["Data", "Web"]
)

# NOT in values
~df["department"].isin(
    ["Data", "Web"]
)

# Range
df["age"].between(25, 30)

# String
df["name"].str.contains(
    "a",
    case=False,
    na=False
)

# Missing
df["salary"].isna()

# Not missing
df["salary"].notna()

# Professional pattern
df.loc[
    condition,
    ["column1", "column2"]
]

# Filter + sort
df.loc[
    condition,
    ["column1", "column2"]
].sort_values(
    "column1",
    ascending=False
)