A common data-analysis pattern is:
FILTER → SORT → AGGREGATE

In [1]:
#Load Dataset
import pandas as pd

sales = pd.DataFrame({
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25]
})

sales["revenue"] = sales["quantity"] * sales["price"]

sales

    product     category salesperson  quantity  price  revenue
0    Laptop  Electronics         Ali         2   1000     2000
1     Mouse  Accessories        Sara        10     25      250
2  Keyboard  Accessories         Ali         5     50      250
3    Laptop  Electronics        Reza         1   1000     1000
4   Monitor  Electronics        Sara         3    400     1200
5     Mouse  Accessories         Ali        15     25      375
6  Keyboard  Accessories        Reza         8     50      400
7   Monitor  Electronics        Sara         2    400      800
8    Laptop  Electronics        Reza         2   1000     2000
9     Mouse  Accessories        Sara        12     25      300

In [3]:
#Eplore
sales.head()

    product     category salesperson  quantity  price  revenue
0    Laptop  Electronics         Ali         2   1000     2000
1     Mouse  Accessories        Sara        10     25      250
2  Keyboard  Accessories         Ali         5     50      250
3    Laptop  Electronics        Reza         1   1000     1000
4   Monitor  Electronics        Sara         3    400     1200

In [4]:
sales.shape

(10, 6)

In [5]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      10 non-null     str
 1   category     10 non-null     str
 2   salesperson  10 non-null     str
 3   quantity     10 non-null     int64
 4   price        10 non-null     int64
 5   revenue      10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [6]:
sales.describe()

        quantity        price      revenue
count  10.000000    10.000000    10.000000
mean    6.000000   397.500000   857.500000
std     4.944132   440.556782   686.582721
min     1.000000    25.000000   250.000000
25%     2.000000    31.250000   318.750000
50%     4.000000   225.000000   600.000000
75%     9.500000   850.000000  1150.000000
max    15.000000  1000.000000  2000.000000

In [7]:
#Filter + Sort
#Example A: Electronics sales, highest revenue first
sales.loc[sales['category']=='Electronics'].sort_values(by='revenue',ascending=False)

   product     category salesperson  quantity  price  revenue
0   Laptop  Electronics         Ali         2   1000     2000
8   Laptop  Electronics        Reza         2   1000     2000
4  Monitor  Electronics        Sara         3    400     1200
3   Laptop  Electronics        Reza         1   1000     1000
7  Monitor  Electronics        Sara         2    400      800

In [9]:
#Sara’s sales, highest quantity first
sales.loc[sales['salesperson']=='Sara'].sort_values(by='quantity',ascending=False)

   product     category salesperson  quantity  price  revenue
9    Mouse  Accessories        Sara        12     25      300
1    Mouse  Accessories        Sara        10     25      250
4  Monitor  Electronics        Sara         3    400     1200
7  Monitor  Electronics        Sara         2    400      800

In [10]:
#Electronics sold by Sara, highest revenue first
sales.loc[(sales['category']=='Electronics') & (sales['salesperson'] == 'Sara')].sort_values(by='revenue',ascending=False)

   product     category salesperson  quantity  price  revenue
4  Monitor  Electronics        Sara         3    400     1200
7  Monitor  Electronics        Sara         2    400      800

In [12]:
#Filter + Aggregation
#Total revenue from electronics
sales.loc[sales['category'] == 'Electronics','revenue'].sum()

np.int64(7000)

In [13]:
#Average revenue for Sara’s sales
sales.loc[sales['salesperson'] == 'Sara','revenue'].mean()

np.float64(637.5)

In [14]:
#Total quantity for Mouse sales
sales.loc[sales['product'] == 'Mouse','quantity'].sum()

np.int64(37)

In [16]:
#Several summaries for electronics
sales.loc[sales['category'] == 'Electronics','revenue'].agg(['sum','min','max'])

sum    7000
min     800
max    2000
Name: revenue, dtype: int64

In [28]:
#Combine all three skills
#For each salesperson, show their electronics sales, sorted by revenue, and calculate the total revenue from those sales.
sales.loc[sales['category'] == 'Electronics'].groupby('salesperson').sum().sort_values(by='revenue',ascending=False)

                    product                category  quantity  price  revenue
salesperson
Reza           LaptopLaptop  ElectronicsElectronics         3   2000     3000
Ali                  Laptop             Electronics         2   1000     2000
Sara         MonitorMonitor  ElectronicsElectronics         5    800     2000

In [21]:
#Filter Mouse sales and sort them by quantity, highest first.
sales.loc[sales['product'] == 'Mouse'].sort_values(by='quantity', ascending=False)

  product     category salesperson  quantity  price  revenue
5   Mouse  Accessories         Ali        15     25      375
9   Mouse  Accessories        Sara        12     25      300
1   Mouse  Accessories        Sara        10     25      250

In [22]:
#Find total revenue from sales where quantity is at least 5.
sales.loc[sales['quantity'] >= 5,'revenue'].sum()

np.int64(1575)

In [23]:
#Find average revenue for Reza’s sales.
sales.loc[sales['salesperson'] == 'Reza','revenue'].mean()

np.float64(1133.3333333333333)

In [24]:
#Filter Accessories sales, sort by price from highest to lowest, and display only product, price, and revenue.
sales.loc[sales['category'] == 'Accessories',['product','price','revenue']].sort_values(by='price',ascending=False)

    product  price  revenue
2  Keyboard     50      250
6  Keyboard     50      400
1     Mouse     25      250
5     Mouse     25      375
9     Mouse     25      300

In [25]:
#Calculate the total revenue from Sara’s Electronics sales.
sales.loc[(sales['salesperson'] == 'Sara') & (sales['category'] == 'Electronics'),'revenue'].sum()

np.int64(2000)

When you receive a business question, identify what it asks you to do:
Which rows? Use filtering with .loc.
What order? Use .sort_values().
What summary? Use .sum(), .mean(), .agg(), or another aggregation.
Summary by category or person? Use .groupby().