groupby() lets Pandas:
Split rows into groups based on a column.
Apply a calculation to each group.
Combine the results into a summary.

In [2]:
#set dataset
import pandas as pd

sales = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Mouse", "Keyboard", "Laptop",
        "Monitor", "Mouse", "Keyboard", "Monitor",
        "Laptop", "Mouse", "Monitor", "Keyboard"
    ],
    "category": [
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Accessories", "Electronics",
        "Electronics", "Accessories", "Electronics", "Accessories"
    ],
    "salesperson": [
        "Ali", "Sara", "Ali", "Reza",
        "Sara", "Ali", "Reza", "Sara",
        "Reza", "Sara", "Ali", "Neda"
    ],
    "region": [
        "North", "South", "West", "East",
        "North", "East", "South", "West",
        "North", "South", "East", "West"
    ],
    "quantity": [2, 10, 5, 1, 3, 15, 8, 2, 2, 12, 4, 6],
    "price": [1000, 25, 50, 1000, 400, 25, 50, 400, 1000, 25, 400, 50]
})

sales["revenue"] = sales["quantity"] * sales["price"]

In [3]:
#Total revenue by product
sales.groupby('product')['revenue'].sum()

product
Keyboard     950
Laptop      5000
Monitor     3600
Mouse        925
Name: revenue, dtype: int64

In [7]:
#The result is a Pandas Series, with product names as the index.
#To turn it into a DataFrame:
sales.groupby('product',as_index=False)['revenue'].sum()
#as_index=False keeps product as a regular column.

    product  revenue
0  Keyboard      950
1    Laptop     5000
2   Monitor     3600
3     Mouse      925

In [9]:
#Let’s show the products with the highest revenue first:
sales.groupby('product',as_index=False)['revenue'].sum().sort_values(by='revenue',ascending=False)

    product  revenue
1    Laptop     5000
2   Monitor     3600
0  Keyboard      950
3     Mouse      925

In [11]:
#How many orders did each product receive?
sales.groupby('product',as_index=False)['order_id'].count()

    product  order_id
0  Keyboard         3
1    Laptop         3
2   Monitor         3
3     Mouse         3

In [12]:
#Multiple calculations with agg()
#Often, one summary is not enough. You may want total revenue, average revenue, quantity sold, and number of orders together.
sales.groupby('product',as_index=False).agg({'revenue':['sum','mean'],'quantity':['sum'],'order_id':['count']})

    product revenue              quantity order_id
                sum         mean      sum    count
0  Keyboard     950   316.666667       19        3
1    Laptop    5000  1666.666667        5        3
2   Monitor    3600  1200.000000        9        3
3     Mouse     925   308.333333       37        3

In [13]:
#Try it: revenue by salesperson
#Total revenue
#Average order revenue
#Total quantity sold
#Number of orders
sales.groupby('salesperson').agg({'revenue':['sum','mean'],'quantity':['sum'],'order_id':['count']})

            revenue              quantity order_id
                sum         mean      sum    count
salesperson
Ali            4225  1056.250000       26        4
Neda            300   300.000000        6        1
Reza           3400  1133.333333       11        3
Sara           2550   637.500000       27        4

In [15]:
#Combine filtering + grouping + sorting
#In the North and East regions, how much revenue did each product generate? Show the highest-revenue product first.
sales.loc[sales['region'].isin(['North','East'])].groupby('product',as_index=False)['revenue'].sum().sort_values(by='revenue',ascending=False)

   product  revenue
0   Laptop     5000
1  Monitor     2800
2    Mouse      375

In [16]:
#mini challenge
#Revenue by region: Group by region and calculate total revenue. Sort from highest to lowest.
sales.groupby('region',as_index=False)['revenue'].sum().sort_values(by='revenue',ascending=False)

  region  revenue
1  North     5200
0   East     2975
3   West     1350
2  South      950

In [24]:
#Product performance: Group by product and calculate total revenue, average revenue, and total quantity.
sales.groupby('product',as_index=False).agg(
    total_revenue=('revenue','sum'),
    average_revenue=('revenue','mean'),
    total_quantity=('quantity','sum')
)

    product  total_revenue  average_revenue  total_quantity
0  Keyboard            950       316.666667              19
1    Laptop           5000      1666.666667               5
2   Monitor           3600      1200.000000               9
3     Mouse            925       308.333333              37

In [30]:
#Analyst question: Filter to the South and West regions, then group by salesperson and calculate total revenue. Sort descending.
sales.loc[sales['region'].isin(['South','West'])].groupby('salesperson',as_index=False).agg(
    total_revenue=('revenue','sum')
).sort_values('total_revenue')

  salesperson  total_revenue
0         Ali            250
1        Neda            300
2        Reza            400
3        Sara           1350

Filter → Group → Aggregate → Sort