In [1]:
#create our dataframe
import pandas as pd

employees = pd.DataFrame({
    "name": [
        "Ali", "Sara", "Reza", "Maryam",
        "Hassan", "Neda", "Omid", "Zahra"
    ],
    "department": [
        "Data", "Web", "Data", "Backend",
        "Web", "Data", "Backend", "Web"
    ],
    "age": [25, 31, 28, 35, 24, 29, 32, 27],
    "salary": [2500, 3200, 2800, 4100, 2300, 3500, 3900, 3000],
    "experience": [2, 5, 3, 8, 1, 6, 7, 4],
    "performance": [82, 91, 76, 95, 68, 88, 93, 85]
})

employees

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
2    Reza       Data   28    2800           3           76
3  Maryam    Backend   35    4100           8           95
4  Hassan        Web   24    2300           1           68
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93
7   Zahra        Web   27    3000           4           85

In [3]:
#basic sorting
employees.sort_values('age')

     name department  age  salary  experience  performance
4  Hassan        Web   24    2300           1           68
0     Ali       Data   25    2500           2           82
7   Zahra        Web   27    3000           4           85
2    Reza       Data   28    2800           3           76
5    Neda       Data   29    3500           6           88
1    Sara        Web   31    3200           5           91
6    Omid    Backend   32    3900           7           93
3  Maryam    Backend   35    4100           8           95

In [4]:
#by default sort is ascending
#descending sort
employees.sort_values('age',ascending=False)

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
1    Sara        Web   31    3200           5           91
5    Neda       Data   29    3500           6           88
2    Reza       Data   28    2800           3           76
7   Zahra        Web   27    3000           4           85
0     Ali       Data   25    2500           2           82
4  Hassan        Web   24    2300           1           68

In [5]:
#Practice 1
#Sort employees by performance, lowest to highest.
employees.sort_values('performance')

     name department  age  salary  experience  performance
4  Hassan        Web   24    2300           1           68
2    Reza       Data   28    2800           3           76
0     Ali       Data   25    2500           2           82
7   Zahra        Web   27    3000           4           85
5    Neda       Data   29    3500           6           88
1    Sara        Web   31    3200           5           91
6    Omid    Backend   32    3900           7           93
3  Maryam    Backend   35    4100           8           95

In [6]:
#Sort employees by performance, highest to lowest.
employees.sort_values('performance',ascending=False)

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
1    Sara        Web   31    3200           5           91
5    Neda       Data   29    3500           6           88
7   Zahra        Web   27    3000           4           85
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
4  Hassan        Web   24    2300           1           68

In [7]:
#Sorting Multiple Columns
employees.sort_values(['performance','salary'])

     name department  age  salary  experience  performance
4  Hassan        Web   24    2300           1           68
2    Reza       Data   28    2800           3           76
0     Ali       Data   25    2500           2           82
7   Zahra        Web   27    3000           4           85
5    Neda       Data   29    3500           6           88
1    Sara        Web   31    3200           5           91
6    Omid    Backend   32    3900           7           93
3  Maryam    Backend   35    4100           8           95

1. Sort by performance
2. If performance is equal,
   sort by salary

In [9]:
#Performance: highest first, and Salary: lowest first
employees.sort_values(['performance','salary'],ascending=[False,True])

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
1    Sara        Web   31    3200           5           91
5    Neda       Data   29    3500           6           88
7   Zahra        Web   27    3000           4           85
0     Ali       Data   25    2500           2           82
2    Reza       Data   28    2800           3           76
4  Hassan        Web   24    2300           1           68

In [10]:
#Practice 2
#department → A-Z
#salary → high to low
employees.sort_values(['department','salary'],ascending=[True,False])

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
5    Neda       Data   29    3500           6           88
2    Reza       Data   28    2800           3           76
0     Ali       Data   25    2500           2           82
1    Sara        Web   31    3200           5           91
7   Zahra        Web   27    3000           4           85
4  Hassan        Web   24    2300           1           68

In [11]:
#experience → high to low
#performance → high to low
employees.sort_values(['experience','performance'],ascending=[False,False])

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
5    Neda       Data   29    3500           6           88
1    Sara        Web   31    3200           5           91
7   Zahra        Web   27    3000           4           85
2    Reza       Data   28    2800           3           76
0     Ali       Data   25    2500           2           82
4  Hassan        Web   24    2300           1           68

In [12]:
#Sorting Strings
#This sorts alphabetically.
employees.sort_values('name')

     name department  age  salary  experience  performance
0     Ali       Data   25    2500           2           82
4  Hassan        Web   24    2300           1           68
3  Maryam    Backend   35    4100           8           95
5    Neda       Data   29    3500           6           88
6    Omid    Backend   32    3900           7           93
2    Reza       Data   28    2800           3           76
1    Sara        Web   31    3200           5           91
7   Zahra        Web   27    3000           4           85

In [13]:
employees.sort_values(['department','name'])

     name department  age  salary  experience  performance
3  Maryam    Backend   35    4100           8           95
6    Omid    Backend   32    3900           7           93
0     Ali       Data   25    2500           2           82
5    Neda       Data   29    3500           6           88
2    Reza       Data   28    2800           3           76
4  Hassan        Web   24    2300           1           68
1    Sara        Web   31    3200           5           91
7   Zahra        Web   27    3000           4           85

In [14]:
#Missing Values While Sorting
#Create missing values
employees.loc[2, "salary"] = None
employees.loc[5, "performance"] = None

In [15]:
employees.sort_values('salary')

     name department  age  salary  experience  performance
4  Hassan        Web   24  2300.0           1         68.0
0     Ali       Data   25  2500.0           2         82.0
7   Zahra        Web   27  3000.0           4         85.0
1    Sara        Web   31  3200.0           5         91.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0
3  Maryam    Backend   35  4100.0           8         95.0
2    Reza       Data   28     NaN           3         76.0

In [17]:
#Pandas normally places missing values at the bottom.
#control NaN position in sort
employees.sort_values('salary',na_position='first')

     name department  age  salary  experience  performance
2    Reza       Data   28     NaN           3         76.0
4  Hassan        Web   24  2300.0           1         68.0
0     Ali       Data   25  2500.0           2         82.0
7   Zahra        Web   27  3000.0           4         85.0
1    Sara        Web   31  3200.0           5         91.0
5    Neda       Data   29  3500.0           6          NaN
6    Omid    Backend   32  3900.0           7         93.0
3  Maryam    Backend   35  4100.0           8         95.0

In [19]:
#Sorting Index with sort_index()
#sort based on dataframe index
employees.sort_index(ascending=False)

     name department  age  salary  experience  performance
7   Zahra        Web   27  3000.0           4         85.0
6    Omid    Backend   32  3900.0           7         93.0
5    Neda       Data   29  3500.0           6          NaN
4  Hassan        Web   24  2300.0           1         68.0
3  Maryam    Backend   35  4100.0           8         95.0
2    Reza       Data   28     NaN           3         76.0
1    Sara        Web   31  3200.0           5         91.0
0     Ali       Data   25  2500.0           2         82.0

In [20]:
#Sorting After Filtering
#Show Data employees and rank them by performance.
employees.loc[employees['department']=='Data'].sort_values('performance',ascending=False)

   name department  age  salary  experience  performance
0   Ali       Data   25  2500.0           2         82.0
2  Reza       Data   28     NaN           3         76.0
5  Neda       Data   29  3500.0           6          NaN

In [21]:
#Top N / Bottom N
#Suppose you want the top 3 performers.
employees.sort_values('performance',ascending=False).head(3)

     name department  age  salary  experience  performance
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
1    Sara        Web   31  3200.0           5         91.0

In [22]:
#worst 3 performance
employees.sort_values('performance',ascending=False).tail(3)

     name department  age  salary  experience  performance
2    Reza       Data   28     NaN           3         76.0
4  Hassan        Web   24  2300.0           1         68.0
5    Neda       Data   29  3500.0           6          NaN

In [23]:
#nlargest()
employees.nlargest(3,'performance')

     name department  age  salary  experience  performance
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
1    Sara        Web   31  3200.0           5         91.0

In [24]:
#nsmallest
employees.nsmallest(3,'performance')

     name department  age  salary  experience  performance
4  Hassan        Web   24  2300.0           1         68.0
2    Reza       Data   28     NaN           3         76.0
0     Ali       Data   25  2500.0           2         82.0

In [28]:
#Custom Sorting
#Data → highest priority
#Backend → second
#Web → third
#Alphabetical sorting won't give us that.
#We can craete categorical order
department_order = pd.CategoricalDtype(['Data','Backend','Web'], ordered=True)
#change column type
employees["department"] = employees[
    "department"
].astype(department_order)
#sort
employees.sort_values("department")

     name department  age  salary  experience  performance
0     Ali       Data   25  2500.0           2         82.0
2    Reza       Data   28     NaN           3         76.0
5    Neda       Data   29  3500.0           6          NaN
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
1    Sara        Web   31  3200.0           5         91.0
4  Hassan        Web   24  2300.0           1         68.0
7   Zahra        Web   27  3000.0           4         85.0

In [29]:
#Final Challenge
#salary → highest to lowest
employees.sort_values('salary',ascending=False)

     name department  age  salary  experience  performance
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
5    Neda       Data   29  3500.0           6          NaN
1    Sara        Web   31  3200.0           5         91.0
7   Zahra        Web   27  3000.0           4         85.0
0     Ali       Data   25  2500.0           2         82.0
4  Hassan        Web   24  2300.0           1         68.0
2    Reza       Data   28     NaN           3         76.0

In [30]:
#department → alphabetical
#salary → highest to lowest
employees.sort_values(['department','salary'],ascending=[True,False])

     name department  age  salary  experience  performance
5    Neda       Data   29  3500.0           6          NaN
0     Ali       Data   25  2500.0           2         82.0
2    Reza       Data   28     NaN           3         76.0
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
1    Sara        Web   31  3200.0           5         91.0
7   Zahra        Web   27  3000.0           4         85.0
4  Hassan        Web   24  2300.0           1         68.0

In [31]:
#Find the top 3 performers.
employees.nlargest(3,'performance')

     name department  age  salary  experience  performance
3  Maryam    Backend   35  4100.0           8         95.0
6    Omid    Backend   32  3900.0           7         93.0
1    Sara        Web   31  3200.0           5         91.0

Show only Data employees, with:
name
salary
performance
and sort them by:
performance → highest to lowest
salary → highest to lowest

In [35]:
employees.loc[:,['name','salary','performance']].sort_values(['performance','salary'],ascending=[False,False])

     name  salary  performance
3  Maryam  4100.0         95.0
6    Omid  3900.0         93.0
1    Sara  3200.0         91.0
7   Zahra  3000.0         85.0
0     Ali  2500.0         82.0
2    Reza     NaN         76.0
4  Hassan  2300.0         68.0
5    Neda  3500.0          NaN

"Give me the Data and Backend employees with at least 2 years of experience. I want the highest performers first. If two employees have the same performance, show the higher-paid employee first. I only need name, department, experience, salary, and performance."

In [38]:
employees.loc[
    (employees['department'].isin(['Data','Backend'])) & 
    (employees['experience'] >= 2),
    ['name','department','experience','salary','performance']
].sort_values(['performance','salary'],ascending=[False,False])

     name department  experience  salary  performance
3  Maryam    Backend           8  4100.0         95.0
6    Omid    Backend           7  3900.0         93.0
0     Ali       Data           2  2500.0         82.0
2    Reza       Data           3     NaN         76.0
5    Neda       Data           6  3500.0          NaN

CHEAT SHEET
# Ascending
df.sort_values("salary")

# Descending
df.sort_values(
    "salary",
    ascending=False
)

# Multiple columns
df.sort_values(
    ["performance", "salary"]
)

# Different directions
df.sort_values(
    ["performance", "salary"],
    ascending=[False, True]
)

# Missing values first
df.sort_values(
    "salary",
    na_position="first"
)

# Missing values last
df.sort_values(
    "salary",
    na_position="last"
)

# Sort by index
df.sort_index()

# Descending index
df.sort_index(
    ascending=False
)

# Filter + sort
df[
    df["department"] == "Data"
].sort_values(
    "performance",
    ascending=False
)

# Filter + select + sort
df.loc[
    condition,
    ["name", "salary"]
].sort_values(
    "salary",
    ascending=False
)

# Top N
df.sort_values(
    "performance",
    ascending=False
).head(3)

# Top N - convenient
df.nlargest(
    3,
    "performance"
)

# Bottom N
df.nsmallest(
    3,
    "performance"
)